version: '3.8'
services:
  db:
    image: postgis/postgis:10-3.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=mva
    ports:
      - '5432:5432'
    volumes:
      - ../Database/mva_dump.sql:/docker-entrypoint-initdb.d/
    networks:
      - va-network
  api:
    build:
      context: ../API
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start"]
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_HOST=db
    depends_on:
      - db
    links:
      - db:db
    networks:
      - va-network
  ui:
    build:
      context: ../UI
      dockerfile: Dockerfile
    entrypoint: ["node", "server.js"]
    environment:
      - API_URL=api
    ports:
      - "3000:3000"
    depends_on:
      - api
    links:
      - api:api
    networks:
      - va-network
  nginx-proxy:
    depends_on:
        - ui
        - api
    image: nginx:alpine
    volumes:
        - $PWD/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 1234:80
    networks:
      - va-network
networks:
  va-network:

