version: "3.8"
services:
  db:
    build:
      context: ../Database
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=mva-uat
    ports:
      - "5432:5432"
    networks:
      - va-network-uat
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db-migrations:
    build:
      context: ../API
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "migrations:runallprod"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=mva-uat
      # - POSTGRES_USER=$VA_DB_USER
      # - POSTGRES_PASSWORD=$VA_DB_PASSWORD
      # - POSTGRES_HOST=vectoratlas-db.postgres.database.azure.com
      # - POSTGRES_DB=postgres
      # - DB_ENCRYPT_CONNECTION=true
    depends_on:
      - db
    networks:
      - va-network-uat
  api:
    build:
      context: ../API
      dockerfile: Dockerfile
    entrypoint: ["node", "dist/src/main.js"]
    restart: always
    volumes:
      - ../API/public:/usr/src/app/dist/public
      - /etc/vector-atlas/api:/etc/vector-atlas/api
      - ../TileServer/data:/data
    environment:
      # - POSTGRES_USER=$VA_DB_USER
      # - POSTGRES_PASSWORD=$VA_DB_PASSWORD
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_HOST=vectoratlas-db.postgres.database.azure.com
      - POSTGRES_DB=postgres
      - DB_ENCRYPT_CONNECTION=true
      - PUBLIC_FOLDER=/usr/src/app/dist
      - CONFIG_FOLDER=/etc/vector-atlas/api
      - AUTH0_ISSUER_URL=https://dev-326tk4zu.us.auth0.com/
      - AUTH0_AUDIENCE=https://www.vectoratlas.org
      # - TOKEN_KEY=$VA_TOKEN_SECRET
      - TOKEN_KEY=yourkey
      - TILESERVER_DATA_FOLDER=/data/
      - OVERLAY_BLOB_FOLDER=/data/blobStore/
      # - AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
      # - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - AZURE_STORAGE_CONNECTION_STRING=azure_conn_string
      - EMAIL_PASSWORD=email_password
      - AUTH0_CLIENT_ID=sQPoZzmH4QaAHVEJrDaK3pPeHG0SmCtr
      # - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
      # - ANALYTICS_ADMIN_PASSWORD=$ANALYTICS_ADMIN_PASSWORD
      - AUTH0_CLIENT_SECRET=your_client_secret
      - ANALYTICS_ADMIN_PASSWORD=your_admin_password
      - ANALYTICS_API_URL=http://analytics:3000/analytics/api
      - NEXT_PUBLIC_ANALYTICS_ID=2b3b6da0-3e75-4d9e-be86-d588496a174e
    depends_on:
      - db-migrations
    networks:
      - va-network-uat
  ui:
    build:
      context: ../UI
      dockerfile: Dockerfile
    entrypoint: ["node", "server.js"]
    restart: always
    environment:
      - API_URL=api
      # - NEXT_PUBLIC_TOKEN_KEY=$VA_TOKEN_SECRET
      - NEXT_PUBLIC_TOKEN_KEY=va_token_secret
      - NEXT_PUBLIC_AUTH_ENDPOINT='http://api:3001/auth/token'
    depends_on:
      - api
    links:
      - api:api
    networks:
      - va-network-uat
  help:
    build:
      context: ../Help
      dockerfile: Dockerfile
    networks:
      - va-network-uat
    entrypoint: ["nginx", "-g", "daemon off;"]
    restart: always
  tileserver:
    build:
      context: ../TileServer
      dockerfile: Dockerfile
    volumes:
      - ../TileServer/data:/data
    networks:
      - va-network-uat
    restart: always
  analytics:
    build:
      context: ./umami
      dockerfile: Dockerfile
      args:
        - BASE_PATH=/analytics
    environment:
      # DATABASE_URL: $VA_DB_URL
      DATABASE_URL: db_url
      DATABASE_TYPE: postgresql
      BASE_PATH: /analytics
      CLIENT_IP_HEADER: "x-original-ip"
    restart: always
    networks:
      - va-network-uat
  nginx-proxy:
    depends_on:
      - ui
      - api
      - help
      - tileserver
      - analytics
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3003:80
    networks:
      - va-network-uat
    restart: always
  python-backend:
    restart: unless-stopped
    build:
      context: ../IngestionAPI/
      dockerfile: Dockerfile
    ports:
      - 8090:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - va-network-uat
networks:
  va-network-uat:

volumes:
  postgres-data:
