version: '3.8'
services:
  api:
    build:
      context: ../API
      dockerfile: Dockerfile
    entrypoint: [ "node", "dist/src/main.js" ]
    restart: always
    volumes:
    - ../API/public:/usr/src/app/dist/public
    environment:
      - POSTGRES_USER=$VA_DB_USER
      - POSTGRES_PASSWORD=$VA_DB_PASSWORD
      - POSTGRES_HOST=vectoratlas-db.postgres.database.azure.com
      - POSTGRES_DB=postgres
      - DB_ENCRYPT_CONNECTION=true
      - PUBLIC_FOLDER=/usr/src/app/dist
      - AUTH0_ISSUER_URL=https://dev-326tk4zu.us.auth0.com/
      - AUTH0_AUDIENCE=https://www.vectoratlas.org
      - TOKEN_KEY=<token-key>
    networks:
      - va-network
  ui:
    build:
      context: ../UI
      dockerfile: Dockerfile
    entrypoint: ['node', 'server.js']
    restart: always
    environment:
      - API_URL=api
    depends_on:
      - api
    links:
      - api:api
    networks:
      - va-network
  help:
    build:
      context: ../Help
      dockerfile: Dockerfile
    networks:
      - va-network
    entrypoint: ['nginx', '-g', 'daemon off;']
    restart: always
  tileserver:
    image: maptiler/tileserver-gl
    volumes:
      - ../TileServer/data:/data
    networks:
      - va-network
    restart: always
  nginx-proxy:
    depends_on:
      - ui
      - api
      - help
      - tileserver
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - va-network
    restart: always
networks:
  va-network: