version: '3.8'
services:
  db:
    build:
      context: ../Database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=mva
    networks:
      - va-network
  api:
    build:
      context: ../API
      dockerfile: Dockerfile
      command: npm run dev:watch
    entrypoint: [ "node", "dist/src/main.js" ]
    ports:
      - "3001:3001"
    volumes:
    - ../API/public/feature_flags.json:/vector-api/assets/feature_flags.json
    - ../API/public/feature_flags.json:/vector-api/assets/map_styles.json
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_HOST=db
      - POSTGRES_DB=mva
      - PUBLIC_FOLDER=/usr/src/app/dist
    depends_on:
      - db
      - ui
    links:
      - db:db
      - ui:ui
    networks:
      - va-network
  ui:
    build:
      context: ../UI
      dockerfile: Dockerfile
    entrypoint: ['node', 'server.js']
    environment:
      - API_URL=api
    ports:
      - '3000:3000'
    depends_on:
      - api
    links:
      - api:api
    networks:
      - va-network
  help:
    build:
      context: ../Help
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    networks:
      - va-network
    entrypoint: ['nginx', '-g', 'daemon off;']
  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - '8080:80'
    volumes:
      - ../TileServer/data:/data 
    networks:
      - va-network
  nginx-proxy:
    depends_on:
      - ui
      - api
      - help
      - tileserver
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1234:80
    networks:
      - va-network
networks:
  va-network: