version: '3.8'
services:
  db:
    build:
      context: ../Database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=mva
    networks:
      - va-network
  api:
    build:
      context: ../API
      dockerfile: Dockerfile
    entrypoint: [ "node", "dist/src/main.js" ]
    volumes:
    - ../API/public:/usr/src/app/dist/public
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_HOST=db
      - POSTGRES_DB=mva
      - PUBLIC_FOLDER=/usr/src/app/dist
      - AUTH0_ISSUER_URL=https://dev-326tk4zu.us.auth0.com/
      - AUTH0_AUDIENCE=https://www.vectoratlas.org
      - TOKEN_KEY=LmUVODxYxi74zcpxk1rha+H7QUo=
    depends_on:
      - db
    links:
      - db:db
    networks:
      - va-network
  ui:
    build:
      context: ../UI
      dockerfile: Dockerfile
    entrypoint: ['node', 'server.js']
    environment:
      - API_URL=api
    ports:
      - '3000:3000'
    depends_on:
      - api
    links:
      - api:api
    networks:
      - va-network
  help:
    build:
      context: ../Help
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    networks:
      - va-network
    entrypoint: ['nginx', '-g', 'daemon off;']
  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - '8080:80'
    volumes:
      - ../TileServer/data:/data
    networks:
      - va-network
  nginx-proxy:
    depends_on:
      - ui
      - api
      - help
      - tileserver
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1234:80
    networks:
      - va-network
networks:
  va-network: