const countries = [
  {
    id: 'country-dz',
    owner: 'system',
    updater: 'system',
    name: 'Algeria',
    iso_code_2: 'DZ',
    iso_code_3: 'DZA',
    alternative_names: [],
  },
  {
    id: 'country-ao',
    owner: 'system',
    updater: 'system',
    name: 'Angola',
    iso_code_2: 'AO',
    iso_code_3: 'AGO',
    alternative_names: [],
  },
  {
    id: 'country-bj',
    owner: 'system',
    updater: 'system',
    name: 'Benin',
    iso_code_2: 'BJ',
    iso_code_3: 'BEN',
    alternative_names: [],
  },
  {
    id: 'country-bw',
    owner: 'system',
    updater: 'system',
    name: 'Botswana',
    iso_code_2: 'BW',
    iso_code_3: 'BWA',
    alternative_names: [],
  },
  {
    id: 'country-bf',
    owner: 'system',
    updater: 'system',
    name: 'Burkina Faso',
    iso_code_2: 'BF',
    iso_code_3: 'BFA',
    alternative_names: [],
  },
  {
    id: 'country-bi',
    owner: 'system',
    updater: 'system',
    name: 'Burundi',
    iso_code_2: 'BI',
    iso_code_3: 'BDI',
    alternative_names: [],
  },
  {
    id: 'country-cv',
    owner: 'system',
    updater: 'system',
    name: 'Cape Verde',
    iso_code_2: 'CV',
    iso_code_3: 'CPV',
    alternative_names: ['Cabo Verde'],
  },
  {
    id: 'country-cm',
    owner: 'system',
    updater: 'system',
    name: 'Cameroon',
    iso_code_2: 'CM',
    iso_code_3: 'CMR',
    alternative_names: [],
  },
  {
    id: 'country-cf',
    owner: 'system',
    updater: 'system',
    name: 'Central African Republic',
    iso_code_2: 'CF',
    iso_code_3: 'CAF',
    alternative_names: [],
  },
  {
    id: 'country-td',
    owner: 'system',
    updater: 'system',
    name: 'Chad',
    iso_code_2: 'TD',
    iso_code_3: 'TCD',
    alternative_names: [],
  },
  {
    id: 'country-km',
    owner: 'system',
    updater: 'system',
    name: 'Comoros',
    iso_code_2: 'KM',
    iso_code_3: 'COM',
    alternative_names: [],
  },
  {
    id: 'country-cg',
    owner: 'system',
    updater: 'system',
    name: 'Republic of the Congo',
    iso_code_2: 'CG',
    iso_code_3: 'COG',
    alternative_names: ['CONGO', 'Congo-Brazzaville'],
  },
  {
    id: 'country-cd',
    owner: 'system',
    updater: 'system',
    name: 'Democratic Republic of the Congo',
    iso_code_2: 'CD',
    iso_code_3: 'COD',
    alternative_names: [
      'DR Congo',
      'Congo-Kinshasa',
      'DRC',
      'DR CONGO',
      'CONGO, THE DEMOCRATIC REPUBLIC',
    ],
  },
  {
    id: 'country-dj',
    owner: 'system',
    updater: 'system',
    name: 'Djibouti',
    iso_code_2: 'DJ',
    iso_code_3: 'DJI',
    alternative_names: [],
  },
  {
    id: 'country-eg',
    owner: 'system',
    updater: 'system',
    name: 'Egypt',
    iso_code_2: 'EG',
    iso_code_3: 'EGY',
    alternative_names: ['Arab Republic of Egypt'],
  },
  {
    id: 'country-gq',
    owner: 'system',
    updater: 'system',
    name: 'Equatorial Guinea',
    iso_code_2: 'GQ',
    iso_code_3: 'GNQ',
    alternative_names: [],
  },
  {
    id: 'country-er',
    owner: 'system',
    updater: 'system',
    name: 'Eritrea',
    iso_code_2: 'ER',
    iso_code_3: 'ERI',
    alternative_names: [],
  },
  {
    id: 'country-sz',
    owner: 'system',
    updater: 'system',
    name: 'Eswatini',
    iso_code_2: 'SZ',
    iso_code_3: 'SWZ',
    alternative_names: ['Swaziland', 'ESTWATINI', 'ESWATINI'],
  },
  {
    id: 'country-et',
    owner: 'system',
    updater: 'system',
    name: 'Ethiopia',
    iso_code_2: 'ET',
    iso_code_3: 'ETH',
    alternative_names: [],
  },
  {
    id: 'country-ga',
    owner: 'system',
    updater: 'system',
    name: 'Gabon',
    iso_code_2: 'GA',
    iso_code_3: 'GAB',
    alternative_names: [],
  },
  {
    id: 'country-gm',
    owner: 'system',
    updater: 'system',
    name: 'Gambia',
    iso_code_2: 'GM',
    iso_code_3: 'GMB',
    alternative_names: ['The Gambia'],
  },
  {
    id: 'country-gh',
    owner: 'system',
    updater: 'system',
    name: 'Ghana',
    iso_code_2: 'GH',
    iso_code_3: 'GHA',
    alternative_names: [],
  },
  {
    id: 'country-gn',
    owner: 'system',
    updater: 'system',
    name: 'Guinea',
    iso_code_2: 'GN',
    iso_code_3: 'GIN',
    alternative_names: [],
  },
  {
    id: 'country-gw',
    owner: 'system',
    updater: 'system',
    name: 'Guinea-Bissau',
    iso_code_2: 'GW',
    iso_code_3: 'GNB',
    alternative_names: ['GUINEA BISSAU'],
  },
  {
    id: 'country-ci',
    owner: 'system',
    updater: 'system',
    name: "Côte d'Ivoire",
    iso_code_2: 'CI',
    iso_code_3: 'CIV',
    alternative_names: ['Ivory Coast', "COTE D'IVOIRE", 'COTE DIVOIRE'],
  },
  {
    id: 'country-ke',
    owner: 'system',
    updater: 'system',
    name: 'Kenya',
    iso_code_2: 'KE',
    iso_code_3: 'KEN',
    alternative_names: [],
  },
  {
    id: 'country-ls',
    owner: 'system',
    updater: 'system',
    name: 'Lesotho',
    iso_code_2: 'LS',
    iso_code_3: 'LSO',
    alternative_names: [],
  },
  {
    id: 'country-lr',
    owner: 'system',
    updater: 'system',
    name: 'Liberia',
    iso_code_2: 'LR',
    iso_code_3: 'LBR',
    alternative_names: [],
  },
  {
    id: 'country-ly',
    owner: 'system',
    updater: 'system',
    name: 'Libya',
    iso_code_2: 'LY',
    iso_code_3: 'LBY',
    alternative_names: ['LYBIA', 'LIBYAN ARAB JAMAHIRIYA'],
  },
  {
    id: 'country-mg',
    owner: 'system',
    updater: 'system',
    name: 'Madagascar',
    iso_code_2: 'MG',
    iso_code_3: 'MDG',
    alternative_names: [],
  },
  {
    id: 'country-mw',
    owner: 'system',
    updater: 'system',
    name: 'Malawi',
    iso_code_2: 'MW',
    iso_code_3: 'MWI',
    alternative_names: [],
  },
  {
    id: 'country-ml',
    owner: 'system',
    updater: 'system',
    name: 'Mali',
    iso_code_2: 'ML',
    iso_code_3: 'MLI',
    alternative_names: [],
  },
  {
    id: 'country-mr',
    owner: 'system',
    updater: 'system',
    name: 'Mauritania',
    iso_code_2: 'MR',
    iso_code_3: 'MRT',
    alternative_names: [],
  },
  {
    id: 'country-mu',
    owner: 'system',
    updater: 'system',
    name: 'Mauritius',
    iso_code_2: 'MU',
    iso_code_3: 'MUS',
    alternative_names: [],
  },
  {
    id: 'country-yt',
    owner: 'system',
    updater: 'system',
    name: 'MAYOTTE',
    iso_code_2: 'YT',
    iso_code_3: 'MYT',
    alternative_names: [],
  },
  {
    id: 'country-ma',
    owner: 'system',
    updater: 'system',
    name: 'Morocco',
    iso_code_2: 'MA',
    iso_code_3: 'MAR',
    alternative_names: [],
  },
  {
    id: 'country-mz',
    owner: 'system',
    updater: 'system',
    name: 'Mozambique',
    iso_code_2: 'MZ',
    iso_code_3: 'MOZ',
    alternative_names: [],
  },
  {
    id: 'country-na',
    owner: 'system',
    updater: 'system',
    name: 'Namibia',
    iso_code_2: 'NA',
    iso_code_3: 'NAM',
    alternative_names: [],
  },
  {
    id: 'country-ne',
    owner: 'system',
    updater: 'system',
    name: 'Niger',
    iso_code_2: 'NE',
    iso_code_3: 'NER',
    alternative_names: [],
  },
  {
    id: 'country-ng',
    owner: 'system',
    updater: 'system',
    name: 'Nigeria',
    iso_code_2: 'NG',
    iso_code_3: 'NGA',
    alternative_names: [],
  },
  {
    id: 'country-rw',
    owner: 'system',
    updater: 'system',
    name: 'Rwanda',
    iso_code_2: 'RW',
    iso_code_3: 'RWA',
    alternative_names: [],
  },
  {
    id: 'country-re',
    owner: 'system',
    updater: 'system',
    name: 'Reunion Island',
    iso_code_2: 'RE',
    iso_code_3: 'REU',
    alternative_names: ['REUNION ISLAND', 'REUNION'],
  },
  {
    id: 'country-st',
    owner: 'system',
    updater: 'system',
    name: 'São Tomé and Príncipe',
    iso_code_2: 'ST',
    iso_code_3: 'STP',
    alternative_names: ['SAO TOME AND PRINCIPE'],
  },
  {
    id: 'country-sn',
    owner: 'system',
    updater: 'system',
    name: 'Senegal',
    iso_code_2: 'SN',
    iso_code_3: 'SEN',
    alternative_names: [],
  },
  {
    id: 'country-sc',
    owner: 'system',
    updater: 'system',
    name: 'Seychelles',
    iso_code_2: 'SC',
    iso_code_3: 'SYC',
    alternative_names: [],
  },
  {
    id: 'country-sl',
    owner: 'system',
    updater: 'system',
    name: 'Sierra Leone',
    iso_code_2: 'SL',
    iso_code_3: 'SLE',
    alternative_names: [],
  },
  {
    id: 'country-so',
    owner: 'system',
    updater: 'system',
    name: 'Somalia',
    iso_code_2: 'SO',
    iso_code_3: 'SOM',
    alternative_names: [],
  },
  {
    id: 'country-za',
    owner: 'system',
    updater: 'system',
    name: 'South Africa',
    iso_code_2: 'ZA',
    iso_code_3: 'ZAF',
    alternative_names: [],
  },
  {
    id: 'country-ss',
    owner: 'system',
    updater: 'system',
    name: 'South Sudan',
    iso_code_2: 'SS',
    iso_code_3: 'SSD',
    alternative_names: [],
  },
  {
    id: 'country-sd',
    owner: 'system',
    updater: 'system',
    name: 'Sudan',
    iso_code_2: 'SD',
    iso_code_3: 'SDN',
    alternative_names: [],
  },
  {
    id: 'country-tz',
    owner: 'system',
    updater: 'system',
    name: 'Tanzania',
    iso_code_2: 'TZ',
    iso_code_3: 'TZA',
    alternative_names: [
      'United Republic of Tanzania',
      'TANZANIA, UNITED REPUBLIC',
    ],
  },
  {
    id: 'country-tg',
    owner: 'system',
    updater: 'system',
    name: 'Togo',
    iso_code_2: 'TG',
    iso_code_3: 'TGO',
    alternative_names: [],
  },
  {
    id: 'country-tn',
    owner: 'system',
    updater: 'system',
    name: 'Tunisia',
    iso_code_2: 'TN',
    iso_code_3: 'TUN',
    alternative_names: [],
  },
  {
    id: 'country-ug',
    owner: 'system',
    updater: 'system',
    name: 'Uganda',
    iso_code_2: 'UG',
    iso_code_3: 'UGA',
    alternative_names: [],
  },
  {
    id: 'country-zm',
    owner: 'system',
    updater: 'system',
    name: 'Zambia',
    iso_code_2: 'ZM',
    iso_code_3: 'ZMB',
    alternative_names: [],
  },
  {
    id: 'country-zw',
    owner: 'system',
    updater: 'system',
    name: 'Zimbabwe',
    iso_code_2: 'ZW',
    iso_code_3: 'ZWE',
    alternative_names: [],
  },
];

export const SANITIZED_COUNTRIES = countries.map((c) => ({
  ...c,
  id: c.name.toUpperCase(), // use name as the id
  name: c.name.toUpperCase(),
  alternative_names: [
    ...c.alternative_names.map((a) => a.toUpperCase()),
    c.name.toUpperCase(),
  ],
}));
