import { MigrationInterface, QueryRunner } from "typeorm";

export class float1661415516312 implements MigrationInterface {
    name = 'float1661415516312'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_n"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_n" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_total"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_total" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_perc"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "daily_survival_rate"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "daily_survival_rate" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "fecundity"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "fecundity" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "gonotrophic_cycle_days"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "gonotrophic_cycle_days" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "ir_by_csp_perc"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "ir_by_csp_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_dissection_perc"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_dissection_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_csp_perc"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_csp_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_p_falciparum"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_p_falciparum" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "oocyst_rate"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "oocyst_rate" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "eir"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "eir" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "eir_days"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "eir_days" double precision`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "indoor_hbr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "indoor_hbr" double precision`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "outdoor_hbr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "outdoor_hbr" double precision`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "combined_hbr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "combined_hbr" double precision`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_biting_n"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_biting_n" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_biting_total"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_biting_total" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_biting_data"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_biting_data" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "outdoor_biting_n"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "outdoor_biting_n" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "outdoor_biting_total"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "outdoor_biting_total" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "outdoor_biting_data"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "outdoor_biting_data" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "unfed_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "unfed_indoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "fed_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "fed_indoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "gravid_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "gravid_indoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "total_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "total_indoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "unfed_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "unfed_outdoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "fed_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "fed_outdoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "gravid_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "gravid_outdoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "total_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "total_outdoor" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "unfed_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "unfed_other" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "fed_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "fed_other" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "gravid_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "gravid_other" double precision`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "total_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "total_other" double precision`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "indoor_host_perc"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "indoor_host_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "outdoor_host_perc"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "outdoor_host_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "combined_host"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "combined_host" double precision`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "host_other"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "host_other" double precision`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "host_other"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "host_other" integer`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "combined_host"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "combined_host" integer`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "outdoor_host_perc"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "outdoor_host_perc" integer`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "indoor_host_perc"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "indoor_host_perc" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "total_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "total_other" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "gravid_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "gravid_other" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "fed_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "fed_other" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "unfed_other"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "unfed_other" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "total_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "total_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "gravid_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "gravid_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "fed_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "fed_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "unfed_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "unfed_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "total_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "total_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "gravid_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "gravid_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "fed_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "fed_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "unfed_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "unfed_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "outdoor_biting_data"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "outdoor_biting_data" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "outdoor_biting_total"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "outdoor_biting_total" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "outdoor_biting_n"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "outdoor_biting_n" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_biting_data"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_biting_data" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_biting_total"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_biting_total" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_biting_n"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_biting_n" integer`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr" integer`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "combined_hbr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "combined_hbr" integer`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "outdoor_hbr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "outdoor_hbr" integer`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "indoor_hbr"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "indoor_hbr" integer`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "eir_days"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "eir_days" integer`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "eir"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "eir" integer`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "oocyst_rate"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "oocyst_rate" integer`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_p_falciparum"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_p_falciparum" integer`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_csp_perc"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_csp_perc" integer`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_dissection_perc"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_dissection_perc" integer`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "ir_by_csp_perc"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "ir_by_csp_perc" integer`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "gonotrophic_cycle_days"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "gonotrophic_cycle_days" integer`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "fecundity"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "fecundity" integer`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "daily_survival_rate"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "daily_survival_rate" integer`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_perc"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_perc" integer`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_total"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_total" integer`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_n"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_n" integer`);
    }

}
