import { MigrationInterface, QueryRunner } from "typeorm";

export class idChange1662019997764 implements MigrationInterface {
    name = 'idChange1662019997764'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_c77d571e529448a04a283924c17"`);
        await queryRunner.query(`ALTER TABLE "sample" DROP CONSTRAINT "PK_1e92238b098b5a4d13f6422cba7"`);
        await queryRunner.query(`ALTER TABLE "sample" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "sample" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sample" ADD CONSTRAINT "PK_1e92238b098b5a4d13f6422cba7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_c8affe6c11913c6e36211174267"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_4440983ad72e1de4e830e586d77"`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "PK_635c0eeabda8862d5b0237b42b4"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "PK_635c0eeabda8862d5b0237b42b4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "site_notes"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "site_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "georef_notes"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "georef_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_4823840f77c01c8be609169e940"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_630b8ed50a5ca7876fd7a321dad"`);
        await queryRunner.query(`ALTER TABLE "species" DROP CONSTRAINT "PK_ae6a87f2423ba6c25dc43c32770"`);
        await queryRunner.query(`ALTER TABLE "species" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "species" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "species" ADD CONSTRAINT "PK_ae6a87f2423ba6c25dc43c32770" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "species" DROP COLUMN "assi_notes"`);
        await queryRunner.query(`ALTER TABLE "species" ADD "assi_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_69457bf7344e306225f91c5bb76"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "PK_db678abc0d87805e345ee35279a"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "PK_db678abc0d87805e345ee35279a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "vector_notes"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "vector_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "referenceId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "referenceId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "siteId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "siteId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "speciesId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "speciesId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "sampleId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "sampleId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_c16633f8b002bd154c433959095"`);
        await queryRunner.query(`ALTER TABLE "reference" DROP CONSTRAINT "PK_01bacbbdd90839b7dce352e4250"`);
        await queryRunner.query(`ALTER TABLE "reference" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reference" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reference" ADD CONSTRAINT "PK_01bacbbdd90839b7dce352e4250" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_f5707b7206f9b94b0e53476909d"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP CONSTRAINT "PK_267213d4d955958ec6ecb053f7a"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "biology" ADD CONSTRAINT "PK_267213d4d955958ec6ecb053f7a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_ef1c9d91807c836c714ce6fd589"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP CONSTRAINT "PK_96f53885cb8e561f8898e3e641b"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "infection" ADD CONSTRAINT "PK_96f53885cb8e561f8898e3e641b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_45afe190a7c60150ad333cdcfa1"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP CONSTRAINT "PK_75651183f2c5e29fd8191426cd0"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD CONSTRAINT "PK_75651183f2c5e29fd8191426cd0" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_6580eea7f5d8cbce7c40bada2a4"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP CONSTRAINT "PK_a10eb8c471145fbf6738b359edf"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD CONSTRAINT "PK_a10eb8c471145fbf6738b359edf" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_da63932571ddc6bda157bd3d8cc"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP CONSTRAINT "PK_04ea47e075b41736e42d402a46b"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD CONSTRAINT "PK_04ea47e075b41736e42d402a46b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_de7b58582f44473a538d91a61ed"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP CONSTRAINT "PK_4abfe8867c98bde6fa0d7457c0a"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD CONSTRAINT "PK_4abfe8867c98bde6fa0d7457c0a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_be07c46beb3c24f41a3a3715596"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "PK_97c382a3550af8e528406eb732b"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "PK_97c382a3550af8e528406eb732b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "control_notes"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "control_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "season_notes"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "season_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "referenceId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "referenceId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "siteId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "siteId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "speciesId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "speciesId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_f5707b7206f9b94b0e53476909d"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "biologyId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "biologyId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_f5707b7206f9b94b0e53476909d" UNIQUE ("biologyId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_ef1c9d91807c836c714ce6fd589"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "infectionId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "infectionId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_ef1c9d91807c836c714ce6fd589" UNIQUE ("infectionId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_45afe190a7c60150ad333cdcfa1"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "bitingRateId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "bitingRateId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_45afe190a7c60150ad333cdcfa1" UNIQUE ("bitingRateId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_be07c46beb3c24f41a3a3715596"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "anthropoZoophagicId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "anthropoZoophagicId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_be07c46beb3c24f41a3a3715596" UNIQUE ("anthropoZoophagicId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_6580eea7f5d8cbce7c40bada2a4"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "endoExophagicId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "endoExophagicId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_6580eea7f5d8cbce7c40bada2a4" UNIQUE ("endoExophagicId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_da63932571ddc6bda157bd3d8cc"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "bitingActivityId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "bitingActivityId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_da63932571ddc6bda157bd3d8cc" UNIQUE ("bitingActivityId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_de7b58582f44473a538d91a61ed"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "endoExophilyId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "endoExophilyId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_de7b58582f44473a538d91a61ed" UNIQUE ("endoExophilyId")`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP CONSTRAINT "PK_91219d23a7713d84209a2c9d2e7"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "id" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD CONSTRAINT "PK_91219d23a7713d84209a2c9d2e7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_69457bf7344e306225f91c5bb76" FOREIGN KEY ("referenceId") REFERENCES "reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_c8affe6c11913c6e36211174267" FOREIGN KEY ("siteId") REFERENCES "site"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_4823840f77c01c8be609169e940" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_c77d571e529448a04a283924c17" FOREIGN KEY ("sampleId") REFERENCES "sample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_c16633f8b002bd154c433959095" FOREIGN KEY ("referenceId") REFERENCES "reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_4440983ad72e1de4e830e586d77" FOREIGN KEY ("siteId") REFERENCES "site"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_630b8ed50a5ca7876fd7a321dad" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_f5707b7206f9b94b0e53476909d" FOREIGN KEY ("biologyId") REFERENCES "biology"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_ef1c9d91807c836c714ce6fd589" FOREIGN KEY ("infectionId") REFERENCES "infection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_45afe190a7c60150ad333cdcfa1" FOREIGN KEY ("bitingRateId") REFERENCES "biting_rate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_be07c46beb3c24f41a3a3715596" FOREIGN KEY ("anthropoZoophagicId") REFERENCES "anthropo_zoophagic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_6580eea7f5d8cbce7c40bada2a4" FOREIGN KEY ("endoExophagicId") REFERENCES "endo_exophagic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_da63932571ddc6bda157bd3d8cc" FOREIGN KEY ("bitingActivityId") REFERENCES "biting_activity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_de7b58582f44473a538d91a61ed" FOREIGN KEY ("endoExophilyId") REFERENCES "endo_exophily"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_de7b58582f44473a538d91a61ed"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_da63932571ddc6bda157bd3d8cc"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_6580eea7f5d8cbce7c40bada2a4"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_be07c46beb3c24f41a3a3715596"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_45afe190a7c60150ad333cdcfa1"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_ef1c9d91807c836c714ce6fd589"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_f5707b7206f9b94b0e53476909d"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_630b8ed50a5ca7876fd7a321dad"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_4440983ad72e1de4e830e586d77"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_c16633f8b002bd154c433959095"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_c77d571e529448a04a283924c17"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_4823840f77c01c8be609169e940"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_c8affe6c11913c6e36211174267"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_69457bf7344e306225f91c5bb76"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP CONSTRAINT "PK_91219d23a7713d84209a2c9d2e7"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD CONSTRAINT "PK_91219d23a7713d84209a2c9d2e7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_de7b58582f44473a538d91a61ed"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "endoExophilyId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "endoExophilyId" uuid`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_de7b58582f44473a538d91a61ed" UNIQUE ("endoExophilyId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_da63932571ddc6bda157bd3d8cc"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "bitingActivityId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "bitingActivityId" uuid`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_da63932571ddc6bda157bd3d8cc" UNIQUE ("bitingActivityId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_6580eea7f5d8cbce7c40bada2a4"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "endoExophagicId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "endoExophagicId" uuid`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_6580eea7f5d8cbce7c40bada2a4" UNIQUE ("endoExophagicId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_be07c46beb3c24f41a3a3715596"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "anthropoZoophagicId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "anthropoZoophagicId" uuid`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_be07c46beb3c24f41a3a3715596" UNIQUE ("anthropoZoophagicId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_45afe190a7c60150ad333cdcfa1"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "bitingRateId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "bitingRateId" uuid`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_45afe190a7c60150ad333cdcfa1" UNIQUE ("bitingRateId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_ef1c9d91807c836c714ce6fd589"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "infectionId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "infectionId" uuid`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_ef1c9d91807c836c714ce6fd589" UNIQUE ("infectionId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_f5707b7206f9b94b0e53476909d"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "biologyId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "biologyId" uuid`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_f5707b7206f9b94b0e53476909d" UNIQUE ("biologyId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "speciesId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "speciesId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "siteId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "siteId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "referenceId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "referenceId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "season_notes"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "season_notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "control_notes"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "control_notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "PK_97c382a3550af8e528406eb732b"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "PK_97c382a3550af8e528406eb732b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_be07c46beb3c24f41a3a3715596" FOREIGN KEY ("anthropoZoophagicId") REFERENCES "anthropo_zoophagic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP CONSTRAINT "PK_4abfe8867c98bde6fa0d7457c0a"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ADD CONSTRAINT "PK_4abfe8867c98bde6fa0d7457c0a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_de7b58582f44473a538d91a61ed" FOREIGN KEY ("endoExophilyId") REFERENCES "endo_exophily"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP CONSTRAINT "PK_04ea47e075b41736e42d402a46b"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD CONSTRAINT "PK_04ea47e075b41736e42d402a46b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_da63932571ddc6bda157bd3d8cc" FOREIGN KEY ("bitingActivityId") REFERENCES "biting_activity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP CONSTRAINT "PK_a10eb8c471145fbf6738b359edf"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD CONSTRAINT "PK_a10eb8c471145fbf6738b359edf" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_6580eea7f5d8cbce7c40bada2a4" FOREIGN KEY ("endoExophagicId") REFERENCES "endo_exophagic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP CONSTRAINT "PK_75651183f2c5e29fd8191426cd0"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD CONSTRAINT "PK_75651183f2c5e29fd8191426cd0" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_45afe190a7c60150ad333cdcfa1" FOREIGN KEY ("bitingRateId") REFERENCES "biting_rate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "infection" DROP CONSTRAINT "PK_96f53885cb8e561f8898e3e641b"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "infection" ADD CONSTRAINT "PK_96f53885cb8e561f8898e3e641b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_ef1c9d91807c836c714ce6fd589" FOREIGN KEY ("infectionId") REFERENCES "infection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "notes" character varying(10485760) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "biology" DROP CONSTRAINT "PK_267213d4d955958ec6ecb053f7a"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "biology" ADD CONSTRAINT "PK_267213d4d955958ec6ecb053f7a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_f5707b7206f9b94b0e53476909d" FOREIGN KEY ("biologyId") REFERENCES "biology"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reference" DROP CONSTRAINT "PK_01bacbbdd90839b7dce352e4250"`);
        await queryRunner.query(`ALTER TABLE "reference" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reference" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reference" ADD CONSTRAINT "PK_01bacbbdd90839b7dce352e4250" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_c16633f8b002bd154c433959095" FOREIGN KEY ("referenceId") REFERENCES "reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "sampleId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "sampleId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "speciesId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "speciesId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "siteId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "siteId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "referenceId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "referenceId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "vector_notes"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "vector_notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "PK_db678abc0d87805e345ee35279a"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "PK_db678abc0d87805e345ee35279a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_69457bf7344e306225f91c5bb76" FOREIGN KEY ("referenceId") REFERENCES "reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "species" DROP COLUMN "assi_notes"`);
        await queryRunner.query(`ALTER TABLE "species" ADD "assi_notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "species" DROP CONSTRAINT "PK_ae6a87f2423ba6c25dc43c32770"`);
        await queryRunner.query(`ALTER TABLE "species" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "species" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "species" ADD CONSTRAINT "PK_ae6a87f2423ba6c25dc43c32770" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_630b8ed50a5ca7876fd7a321dad" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_4823840f77c01c8be609169e940" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "georef_notes"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "georef_notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "site_notes"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "site_notes" character varying(10485760)`);
        await queryRunner.query(`ALTER TABLE "site" DROP CONSTRAINT "PK_635c0eeabda8862d5b0237b42b4"`);
        await queryRunner.query(`ALTER TABLE "site" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "site" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "site" ADD CONSTRAINT "PK_635c0eeabda8862d5b0237b42b4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_4440983ad72e1de4e830e586d77" FOREIGN KEY ("siteId") REFERENCES "site"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_c8affe6c11913c6e36211174267" FOREIGN KEY ("siteId") REFERENCES "site"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sample" DROP CONSTRAINT "PK_1e92238b098b5a4d13f6422cba7"`);
        await queryRunner.query(`ALTER TABLE "sample" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "sample" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "sample" ADD CONSTRAINT "PK_1e92238b098b5a4d13f6422cba7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_c77d571e529448a04a283924c17" FOREIGN KEY ("sampleId") REFERENCES "sample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
