import { MigrationInterface, QueryRunner } from "typeorm";

export class removeLengthConstraints1675850965282 implements MigrationInterface {
    name = 'removeLengthConstraints1675850965282'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "auth0_id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_4" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "control_type" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "country" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "name" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "latitude" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "longitude" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "georef_source" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "admin_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "admin_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "admin_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "latitude_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "longitude_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "latlong_source" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "rural_urban" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "area_type" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "ss_sl" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "id_method_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "id_method_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "id_method_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ALTER COLUMN "dec_id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ALTER COLUMN "dec_check" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ALTER COLUMN "map_check" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_n" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_n" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "eir_period" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_indoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_outdoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_n" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_unit" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_n" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_unit" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ALTER COLUMN "biting_sampling_indoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ALTER COLUMN "biting_sampling_outdoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ALTER COLUMN "biting_unit" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_sampling_indoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_sampling_outdoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_sampling_other" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_unit" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "roof" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "walls" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "cooking" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "occupation_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "occupation_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "occupation_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "farming" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_4" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "local_plants" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "study_sampling_design" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "contact_notes" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "secondary_info" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "control" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "season_given" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "season_calc" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "data_abstracted_by" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "data_checked_by" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_indoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_outdoor" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_n" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_unit" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_3" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_n" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_other_unit" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "species_information" ALTER COLUMN "name" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "species_information" ALTER COLUMN "shortDescription" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "species_information" ALTER COLUMN "distributionMapUrl" TYPE character varying`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "species_information" ALTER COLUMN "distributionMapUrl" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "species_information" ALTER COLUMN "shortDescription" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "species_information" ALTER COLUMN "name" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "news" ALTER COLUMN "title" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_other_unit" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_n" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_other_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_unit" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_n" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_combined_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_outdoor" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ALTER COLUMN "host_sampling_indoor" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "data_checked_by" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "data_abstracted_by" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "season_calc" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "season_given" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "control" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "secondary_info" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "contact_notes" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ALTER COLUMN "study_sampling_design" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "local_plants" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_4" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "livestock_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "farming" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "occupation_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "occupation_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "occupation_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "cooking" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "walls" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "environment" ALTER COLUMN "roof" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_unit" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_sampling_other" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_sampling_outdoor" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" ALTER COLUMN "resting_sampling_indoor" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ALTER COLUMN "biting_unit" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ALTER COLUMN "biting_sampling_outdoor" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ALTER COLUMN "biting_sampling_indoor" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_unit" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_n" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "abr_sampling_combined_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_unit" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_n" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_combined_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_outdoor" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ALTER COLUMN "hbr_sampling_indoor" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "eir_period" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_n" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "infection" ALTER COLUMN "sampling_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_n" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "biology" ALTER COLUMN "sampling_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "occurrence" ALTER COLUMN "map_check" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "occurrence" ALTER COLUMN "dec_check" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "occurrence" ALTER COLUMN "dec_id" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "id_method_3" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "id_method_2" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "id_method_1" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "recorded_species" ALTER COLUMN "ss_sl" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "area_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "rural_urban" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "latlong_source" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "longitude_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "latitude_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "admin_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "admin_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "admin_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "georef_source" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "longitude" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "latitude" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "name" character varying(250) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site" ALTER COLUMN "country" character varying(250) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "control_type" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_4" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_3" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_2" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "sample" ALTER COLUMN "mossamp_tech_1" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "auth0_id" character varying(256) NOT NULL`);
    }

}
