import { MigrationInterface, QueryRunner } from "typeorm";

export class FixRealtionships1722931572152 implements MigrationInterface {
    name = 'FixRealtionships1722931572152'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_aa52ec7238f9cc4b065049209af"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_b7b6e0077e7331785abad7f2b1e"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_f5707b7206f9b94b0e53476909d"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_ef1c9d91807c836c714ce6fd589"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_de7b58582f44473a538d91a61ed"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_da63932571ddc6bda157bd3d8cc"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_c467102526a521fdb7e81713eaf"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_be07c46beb3c24f41a3a3715596"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_6580eea7f5d8cbce7c40bada2a4"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "FK_45afe190a7c60150ad333cdcfa1"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_db66b64387929689e18d4439b1c"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_a63eb2d28736b29d8aaad14a5e5"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_e8ad2170daea8f0776244b6eb31"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_f4391b16d3f962d1d0d6f9faad9"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_a90795d4f2f5fc124894b3b3a84"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_7c6e0bfb4cdb7ab15c3208bb4be"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_5c2dbec8223b1fa5583785a10c3"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_d65340e159b8ad262c2c18eacae"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_c689d9b00b9912fc53d00a3190b"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_753920ae3aa0ae7754ad0554235"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_ab3f4fcff9bf709ff3071ef621b"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_8b283fcfd5356000890d4e630a4"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_d241f1d94efb196f2d9e7ff8906"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_2f3b60260a0b8921963ee18c59a"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_a6faeed18969535c626efcb9811"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_4944017cff3a475b5dea94d4224"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_736b893b14c20855287ea1c27d9"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_edc898abf26192fc4ca2c67ea32"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_63f4d1c7ed32a882a05fbcf8a66"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_65a9c0edce08b53c22c88621a6f"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_433df12576baa25c8231b2e1163"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_535d24774bc5e47c62315acc1b1"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_adaf447d10ae7ea12848c4d33e1"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_71da7c36574477f7f2f8e63b60e"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_44fbde14be988ce4dda121577a9"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_2539c8246b81d7b88b4891f444d"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_9a0f87904bbee0a3f6c9a5e1174"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_f5707b7206f9b94b0e53476909d"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "biologyId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_ef1c9d91807c836c714ce6fd589"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "infectionId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_45afe190a7c60150ad333cdcfa1"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "bitingRateId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_be07c46beb3c24f41a3a3715596"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "anthropoZoophagicId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_6580eea7f5d8cbce7c40bada2a4"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "endoExophagicId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_da63932571ddc6bda157bd3d8cc"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "bitingActivityId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_de7b58582f44473a538d91a61ed"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "endoExophilyId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_c467102526a521fdb7e81713eaf"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "recordedSpeciesId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_b7b6e0077e7331785abad7f2b1e"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "environmentId"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP CONSTRAINT "UQ_aa52ec7238f9cc4b065049209af"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "larvalSiteId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "REL_9a0f87904bbee0a3f6c9a5e117"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "genotypicRepresentativenessId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_2539c8246b81d7b88b4891f444d"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgscMethodAndSampleId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_44fbde14be988ce4dda121577a9"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgscGeneytpeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_71da7c36574477f7f2f8e63b60e"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "kdrGenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_adaf447d10ae7ea12848c4d33e1"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgsc995AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_535d24774bc5e47c62315acc1b1"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgsc402GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_433df12576baa25c8231b2e1163"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgsc402AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_65a9c0edce08b53c22c88621a6f"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "cyp6aapAlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_63f4d1c7ed32a882a05fbcf8a66"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "cyp6aapGenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_edc898abf26192fc4ca2c67ea32"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "cyp6p4AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_736b893b14c20855287ea1c27d9"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "cyp6p4GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_4944017cff3a475b5dea94d4224"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "cyp4j5AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_a6faeed18969535c626efcb9811"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "cyp4j5GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_2f3b60260a0b8921963ee18c59a"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "cytochromesP450CypMethodAndSampleId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_d241f1d94efb196f2d9e7ff8906"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "gste2119AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_8b283fcfd5356000890d4e630a4"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "gste2119GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_ab3f4fcff9bf709ff3071ef621b"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "gste2114AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_753920ae3aa0ae7754ad0554235"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "gste2114GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_c689d9b00b9912fc53d00a3190b"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgsc1570GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_d65340e159b8ad262c2c18eacae"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgsc1570AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_5c2dbec8223b1fa5583785a10c3"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "rdlMethodAndSampleId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_7c6e0bfb4cdb7ab15c3208bb4be"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "rdl296GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_a90795d4f2f5fc124894b3b3a84"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "rdl296AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_f4391b16d3f962d1d0d6f9faad9"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "ace1MethodAndSampleId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_e8ad2170daea8f0776244b6eb31"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "ace1GenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_a63eb2d28736b29d8aaad14a5e5"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "ace1AlleleFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "UQ_db66b64387929689e18d4439b1c"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "gsteMethodAndSampleId"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_f19b66f6cce34efff8d94162bcf"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_c77d571e529448a04a283924c17"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "UQ_f19b66f6cce34efff8d94162bcf"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "UQ_c77d571e529448a04a283924c17"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_f19b66f6cce34efff8d94162bcf" FOREIGN KEY ("recordedSpeciesId") REFERENCES "recorded_species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_c77d571e529448a04a283924c17" FOREIGN KEY ("sampleId") REFERENCES "sample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_c77d571e529448a04a283924c17"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP CONSTRAINT "FK_f19b66f6cce34efff8d94162bcf"`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "UQ_c77d571e529448a04a283924c17" UNIQUE ("sampleId")`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "UQ_f19b66f6cce34efff8d94162bcf" UNIQUE ("recordedSpeciesId")`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_c77d571e529448a04a283924c17" FOREIGN KEY ("sampleId") REFERENCES "sample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD CONSTRAINT "FK_f19b66f6cce34efff8d94162bcf" FOREIGN KEY ("recordedSpeciesId") REFERENCES "recorded_species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "gsteMethodAndSampleId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_db66b64387929689e18d4439b1c" UNIQUE ("gsteMethodAndSampleId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "ace1AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_a63eb2d28736b29d8aaad14a5e5" UNIQUE ("ace1AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "ace1GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_e8ad2170daea8f0776244b6eb31" UNIQUE ("ace1GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "ace1MethodAndSampleId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_f4391b16d3f962d1d0d6f9faad9" UNIQUE ("ace1MethodAndSampleId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "rdl296AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_a90795d4f2f5fc124894b3b3a84" UNIQUE ("rdl296AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "rdl296GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_7c6e0bfb4cdb7ab15c3208bb4be" UNIQUE ("rdl296GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "rdlMethodAndSampleId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_5c2dbec8223b1fa5583785a10c3" UNIQUE ("rdlMethodAndSampleId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgsc1570AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_d65340e159b8ad262c2c18eacae" UNIQUE ("vgsc1570AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgsc1570GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_c689d9b00b9912fc53d00a3190b" UNIQUE ("vgsc1570GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "gste2114GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_753920ae3aa0ae7754ad0554235" UNIQUE ("gste2114GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "gste2114AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_ab3f4fcff9bf709ff3071ef621b" UNIQUE ("gste2114AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "gste2119GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_8b283fcfd5356000890d4e630a4" UNIQUE ("gste2119GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "gste2119AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_d241f1d94efb196f2d9e7ff8906" UNIQUE ("gste2119AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "cytochromesP450CypMethodAndSampleId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_2f3b60260a0b8921963ee18c59a" UNIQUE ("cytochromesP450CypMethodAndSampleId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "cyp4j5GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_a6faeed18969535c626efcb9811" UNIQUE ("cyp4j5GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "cyp4j5AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_4944017cff3a475b5dea94d4224" UNIQUE ("cyp4j5AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "cyp6p4GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_736b893b14c20855287ea1c27d9" UNIQUE ("cyp6p4GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "cyp6p4AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_edc898abf26192fc4ca2c67ea32" UNIQUE ("cyp6p4AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "cyp6aapGenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_63f4d1c7ed32a882a05fbcf8a66" UNIQUE ("cyp6aapGenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "cyp6aapAlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_65a9c0edce08b53c22c88621a6f" UNIQUE ("cyp6aapAlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgsc402AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_433df12576baa25c8231b2e1163" UNIQUE ("vgsc402AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgsc402GenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_535d24774bc5e47c62315acc1b1" UNIQUE ("vgsc402GenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgsc995AlleleFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_adaf447d10ae7ea12848c4d33e1" UNIQUE ("vgsc995AlleleFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "kdrGenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_71da7c36574477f7f2f8e63b60e" UNIQUE ("kdrGenotypeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgscGeneytpeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_44fbde14be988ce4dda121577a9" UNIQUE ("vgscGeneytpeFrequenciesId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgscMethodAndSampleId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "UQ_2539c8246b81d7b88b4891f444d" UNIQUE ("vgscMethodAndSampleId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "genotypicRepresentativenessId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "REL_9a0f87904bbee0a3f6c9a5e117" UNIQUE ("genotypicRepresentativenessId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "larvalSiteId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_aa52ec7238f9cc4b065049209af" UNIQUE ("larvalSiteId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "environmentId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_b7b6e0077e7331785abad7f2b1e" UNIQUE ("environmentId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "recordedSpeciesId" character varying(256) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_c467102526a521fdb7e81713eaf" UNIQUE ("recordedSpeciesId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "endoExophilyId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_de7b58582f44473a538d91a61ed" UNIQUE ("endoExophilyId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "bitingActivityId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_da63932571ddc6bda157bd3d8cc" UNIQUE ("bitingActivityId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "endoExophagicId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_6580eea7f5d8cbce7c40bada2a4" UNIQUE ("endoExophagicId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "anthropoZoophagicId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_be07c46beb3c24f41a3a3715596" UNIQUE ("anthropoZoophagicId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "bitingRateId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_45afe190a7c60150ad333cdcfa1" UNIQUE ("bitingRateId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "infectionId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_ef1c9d91807c836c714ce6fd589" UNIQUE ("infectionId")`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "biologyId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "UQ_f5707b7206f9b94b0e53476909d" UNIQUE ("biologyId")`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_9a0f87904bbee0a3f6c9a5e1174" FOREIGN KEY ("genotypicRepresentativenessId") REFERENCES "genotypicRepresentativeness"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_2539c8246b81d7b88b4891f444d" FOREIGN KEY ("vgscMethodAndSampleId") REFERENCES "vgscMethodAndSample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_44fbde14be988ce4dda121577a9" FOREIGN KEY ("vgscGeneytpeFrequenciesId") REFERENCES "vgscGeneytpeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_71da7c36574477f7f2f8e63b60e" FOREIGN KEY ("kdrGenotypeFrequenciesId") REFERENCES "vgscGeneytpeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_adaf447d10ae7ea12848c4d33e1" FOREIGN KEY ("vgsc995AlleleFrequenciesId") REFERENCES "vgsc995AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_535d24774bc5e47c62315acc1b1" FOREIGN KEY ("vgsc402GenotypeFrequenciesId") REFERENCES "vgsc402GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_433df12576baa25c8231b2e1163" FOREIGN KEY ("vgsc402AlleleFrequenciesId") REFERENCES "vgsc402AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_65a9c0edce08b53c22c88621a6f" FOREIGN KEY ("cyp6aapAlleleFrequenciesId") REFERENCES "cyp6aapAlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_63f4d1c7ed32a882a05fbcf8a66" FOREIGN KEY ("cyp6aapGenotypeFrequenciesId") REFERENCES "cyp6aapGenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_edc898abf26192fc4ca2c67ea32" FOREIGN KEY ("cyp6p4AlleleFrequenciesId") REFERENCES "cyp6p4AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_736b893b14c20855287ea1c27d9" FOREIGN KEY ("cyp6p4GenotypeFrequenciesId") REFERENCES "cyp6p4GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_4944017cff3a475b5dea94d4224" FOREIGN KEY ("cyp4j5AlleleFrequenciesId") REFERENCES "cyp4j5AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_a6faeed18969535c626efcb9811" FOREIGN KEY ("cyp4j5GenotypeFrequenciesId") REFERENCES "cyp4j5GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_2f3b60260a0b8921963ee18c59a" FOREIGN KEY ("cytochromesP450CypMethodAndSampleId") REFERENCES "cytochromesP450_cypMethodAndSample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_d241f1d94efb196f2d9e7ff8906" FOREIGN KEY ("gste2119AlleleFrequenciesId") REFERENCES "gste2_119AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_8b283fcfd5356000890d4e630a4" FOREIGN KEY ("gste2119GenotypeFrequenciesId") REFERENCES "gste2_119GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_ab3f4fcff9bf709ff3071ef621b" FOREIGN KEY ("gste2114AlleleFrequenciesId") REFERENCES "gste2_114AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_753920ae3aa0ae7754ad0554235" FOREIGN KEY ("gste2114GenotypeFrequenciesId") REFERENCES "gste2_114GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_c689d9b00b9912fc53d00a3190b" FOREIGN KEY ("vgsc1570GenotypeFrequenciesId") REFERENCES "vgsc1570GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_d65340e159b8ad262c2c18eacae" FOREIGN KEY ("vgsc1570AlleleFrequenciesId") REFERENCES "vgsc1570AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_5c2dbec8223b1fa5583785a10c3" FOREIGN KEY ("rdlMethodAndSampleId") REFERENCES "rdlMethodAndSample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_7c6e0bfb4cdb7ab15c3208bb4be" FOREIGN KEY ("rdl296GenotypeFrequenciesId") REFERENCES "rdl296GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_a90795d4f2f5fc124894b3b3a84" FOREIGN KEY ("rdl296AlleleFrequenciesId") REFERENCES "rdl296AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_f4391b16d3f962d1d0d6f9faad9" FOREIGN KEY ("ace1MethodAndSampleId") REFERENCES "ace1MethodAndSample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_e8ad2170daea8f0776244b6eb31" FOREIGN KEY ("ace1GenotypeFrequenciesId") REFERENCES "ace1GenotypeFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_a63eb2d28736b29d8aaad14a5e5" FOREIGN KEY ("ace1AlleleFrequenciesId") REFERENCES "ace1AlleleFrequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_db66b64387929689e18d4439b1c" FOREIGN KEY ("gsteMethodAndSampleId") REFERENCES "gsteMethodAndSample"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_45afe190a7c60150ad333cdcfa1" FOREIGN KEY ("bitingRateId") REFERENCES "biting_rate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_6580eea7f5d8cbce7c40bada2a4" FOREIGN KEY ("endoExophagicId") REFERENCES "endo_exophagic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_be07c46beb3c24f41a3a3715596" FOREIGN KEY ("anthropoZoophagicId") REFERENCES "anthropo_zoophagic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_c467102526a521fdb7e81713eaf" FOREIGN KEY ("recordedSpeciesId") REFERENCES "recorded_species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_da63932571ddc6bda157bd3d8cc" FOREIGN KEY ("bitingActivityId") REFERENCES "biting_activity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_de7b58582f44473a538d91a61ed" FOREIGN KEY ("endoExophilyId") REFERENCES "endo_exophily"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_ef1c9d91807c836c714ce6fd589" FOREIGN KEY ("infectionId") REFERENCES "infection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_f5707b7206f9b94b0e53476909d" FOREIGN KEY ("biologyId") REFERENCES "biology"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_b7b6e0077e7331785abad7f2b1e" FOREIGN KEY ("environmentId") REFERENCES "environment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD CONSTRAINT "FK_aa52ec7238f9cc4b065049209af" FOREIGN KEY ("larvalSiteId") REFERENCES "Larval_site"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
