import { MigrationInterface, QueryRunner } from "typeorm";

export class FullDbTablesCheck1773227932949 implements MigrationInterface {
    name = 'FullDbTablesCheck1773227932949'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sample" RENAME COLUMN "occurrence_n_tot" TO "occurrence_n_total"`);
        await queryRunner.query(`ALTER TABLE "vgscMethodAndSample" RENAME COLUMN "vgsc_no_of_mosquitors_tested" TO "vgsc_number_of_mosquitoes_tested"`);
        await queryRunner.query(`ALTER TABLE "vgsc402AlleleFrequencies" RENAME COLUMN "vgsc.402l_percent" TO "vgsc_402l_percent"`);
        await queryRunner.query(`ALTER TABLE "rdlMethodAndSample" RENAME COLUMN "rdl_no_of_mosquitoes_tested" TO "rdl_number_of_mosquitoes_tested"`);
        await queryRunner.query(`ALTER TABLE "ace1MethodAndSample" RENAME COLUMN "ace1_no_of_mosquitoes_tested" TO "ace1_number_of_mosquitoes_tested"`);
        await queryRunner.query(`ALTER TABLE "gsteMethodAndSample" RENAME COLUMN "gste_no_of_mosquitoes_tested" TO "gste_number_of_mosquitoes_tested"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" RENAME COLUMN "sampling_nights_no_indoor" TO "biting_activity_indoor_number_of_sampling_nights"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" RENAME COLUMN "notes" TO "resting_notes"`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "edit_logs" ("id" SERIAL NOT NULL, "occurrenceId" character varying NOT NULL, "initialData" jsonb, "modifiedData" jsonb, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "editor" jsonb, "reasonForEdit" character varying, CONSTRAINT "PK_c769f88150aed540c8beb4db73f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "VgsclVgsc995fVgsc995sVgsc995cGenotypeFrequenciesFormally1014" ("id" character varying(256) NOT NULL, "vgsc995l_vgsc995l_n" character varying, "vgsc995l_vgsc995l_percent" character varying, "vgsc995l_vgsc995f_n" character varying, "vgsc995l_vgsc995f_percent" character varying, "vgsc995f_vgsc995f_n" character varying, "vgsc995f_vgsc995f_percent" character varying, "vgsc995l_vgsc995s_n" character varying, "vgsc995l_vgsc995s_percent" character varying, "vgsc995s_vgsc995s_n" character varying, "vgsc995s_vgsc995s_percent" character varying, "vgsc995l_vgsc995c_n" character varying, "vgsc995l_vgsc995c_percent" character varying, "vgsc995c_vgsc995c_n" character varying, "vgsc995c_vgsc995c_percent" character varying, "null_vgsc995c_or_vgsc995c_vgsc995c_n" character varying, "null_vgsc995c_or_vgsc995c_vgsc995c_percent" character varying, "vgsc995f_vgsc995s_n" character varying, "vgsc995f_vgsc995s_percent" character varying, "vgsc995f_vgsc995c_n" character varying, "vgsc995f_vgsc995c_percent" character varying, CONSTRAINT "PK_906893bf3092e598203156121f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rdl296c_rdl296g_rdl296s_genotype_frequencies" ("id" character varying(256) NOT NULL, "rdl296c_rdl296c__n" character varying, "rdl296c_rdl296c_percent" character varying, "rdl296c_rdl296g_n" character varying, "rdl296c_rdl296g_percent" character varying, "rdl296g_rdl296g_n" character varying, "rdl296g_rdl296g_percent" character varying, "rdl296c_rdl296s_n" character varying, "rdl296c_rdl296s_percent" character varying, "rdl296s_rdl296s_n" character varying, "rdl296s_rdl296s_percent" character varying, "rdl296g_rdl296s_n" character varying, "rdl296g_rdl296s_percent" character varying, CONSTRAINT "PK_343e1b538029ad785703cc0d287" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ace1_genotype_frequencies_formally_119" ("id" character varying(256) NOT NULL, "ace1_number_of_mosquitoes_tested" character varying, "ace1_280g_ace1_280g_n" character varying, "ace1_280g_ace1_280g_percent" character varying, "ace1_280g_ace1_280s_n" character varying, "ace1_280g_ace1_280s_percent" character varying, "ace1_280s_ace1_280s_n" character varying, "ace1_280s_ace1_280s_percent" character varying, CONSTRAINT "PK_050f6ac08082b6adaed975f67af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "gen_test_rep_site"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "gen_test_rep_site_dis"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "minor_spec_miss_alle_freq_data"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "notes_population_rep"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "gen_sample_first_bio_tests"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "gen_sample_link_spec_bio"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "bio_subsample_used_gen_test"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "notes_on_bioessay_linkage"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "susceptible.susceptible_n"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "susceptible.susceptible_percent"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant.susceptible_n"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant.susceptible_percent"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant.resistant_n"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant.resistant_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v.vgsc402v_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v.vgsc402v_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v.vgsc402l_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v.vgsc402l_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402l.vgsc402l_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402l.vgsc402l_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n.vgsc1570n_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n.vgsc1570n_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n.vgsc1570y_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n.1570y_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570y.vgsc1570y_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570y.vgsc1570y_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" DROP COLUMN "cyp6aap.wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" DROP COLUMN "cyp6aap.dup1_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap.wt.cyp6aap.wt_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap.wt.cyp6aap.wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap.wt.cyp6aap.dup1_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap.wt.cyp6aap.dup1_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap.dup1.cyp6aap.dup1_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap.dup1.cyp6aap.dup1_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" DROP COLUMN "cyp6p4.236wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" DROP COLUMN "cyp6p4.236m_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" DROP COLUMN "cyp4j5.43l_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" DROP COLUMN "cyp4j5.43f_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l.cyp4j5_43l_n"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l.cyp4j5_43l_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l.cyp4j5_43f_n"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l.cyp4j5_43f_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43f.cyp4j5_43f_n"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43f.cyp4j5_43f_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l.gste2_119l_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l.gste2_119l_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l.gste2_119v_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l.gste2_119v_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119v.gste2_119v_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119v.gste2_119v_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I.gste2_114I_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I.gste2_114I_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I.gste2_114t_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I.gste2_114t_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114t.gste2_114t_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114t.gste2_114t_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4.236wt_cyp6p4.236wt_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4.236wt_cyp6p4.236wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4.236wt_cyp6p4.236m_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4.236wt_cyp6p4.236m_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4.236m_cyp6p4.236m_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4.236m_cyp6p4.236m_percent"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "bio_rep_complex_site"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "bio_rep_complex_site_disaggregated"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "wild_caught_larvae_adults"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "test_protocal"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "concentration_microgram"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "mosquitors_tested_n"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "mosquitors_dead_n"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "knock_down_expo_time_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "no_mosq_knock_down"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "ir_data"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_1"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_2"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_3"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_n"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_perc"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "daily_survival_rate"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "fecundity"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_1"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_2"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_3"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_dissection_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_dissection_total"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_csp_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_csp_total"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_pf_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_pf_total"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_csp_perc"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "occupation_1"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "occupation_2"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "occupation_3"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "average_waketime"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "leave_home_time"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "hours_away"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "outdoor_activities_night"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_performance_1"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_vegetation_2"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_performance_2"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_tubidity_3"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_performance_3"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "genotypic_test_representative_of_species_at_site" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "genotypic_test_representative_of_species_at_site_if_disaggregated_values_combined_without_adjustments" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "minor_species_missing_allele_frequency_data" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "notes_on_population_representative" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "genotypic_sample_first_been_through_bioassay_tests" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "genotypic_sample_linked_to_a_specific_bioassay" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "bioassay_subsample_used_in_genotypic_test" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "notes_on_bioassay_linkage" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "susceptible_susceptible_n" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "susceptible_susceptible_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant_susceptible_n" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant_susceptible_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant_resistant_n" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant_resistant_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v_vgsc402v_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v_vgsc402v_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v_vgsc402l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v_vgsc402l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402l_vgsc402l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402l_vgsc402l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n_vgsc1570n_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n_vgsc1570n_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n_vgsc1570y_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n_1570y_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570y_vgsc1570y_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570y_vgsc1570y_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" ADD "cyp6aap_wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" ADD "cyp6aap_dup1_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt_cyp6aap.wt_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt.cyp6aap_wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt_cyp6aap_dup1_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt_cyp6aap_dup1_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_dup1_cyp6aap_dup1_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_dup1_cyp6aap_dup1_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" ADD "cyp6p4_236wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" ADD "cyp6p4_236m_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" ADD "cyp4j5_43l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" ADD "cyp4j5_43f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l_cyp4j5_43l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l_cyp4j5_43l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l_cyp4j5_43f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l_cyp4j5_43f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43f_cyp4j5_43f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43f_cyp4j5_43f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l_gste2_119l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l_gste2_119l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l_gste2_119v_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l_gste2_119v_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119v_gste2_119v_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119v_gste2_119v_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I_gste2_114I_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I_gste2_114I_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I_gste2_114t_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I_gste2_114t_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114t_gste2_114t_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114t_gste2_114t_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4_236wt_cyp6p4_236wt_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4_236wt_cyp6p4_236wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4_236wt_cyp6p4_236m_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4_236wt_cyp6p4_236m_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4_236m_cyp6p4_236m_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4_236m_cyp6p4_236m_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "bioassay_representative_of_complex_at_site" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "bioassay_representative_of_complex_at_site_if_disaggregated_values_combined_without_adjustments" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "wild_caught_larvae_or_adults" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "test_protocol" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "concentration_micrograms" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "mosquitoes_tested_n" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "mosquitoes_dead_n" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "knock_down_exposure_time_min" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "mosquitoes_knocked_down_n" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "vgsc995GenotypeFrequenciesFormally1014Id" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "rdl296cRdl296gRdl296sGenotypeFrequenciesId" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "ace1GenotypeFrequenciesFormally119Id" character varying(256)`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "insecticide_resistance_data" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "binary_absence" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "citation_doi" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_biology_1" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_biology_2" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_biology_3" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_biology_n" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_percent" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "daily_survival_rate_percent" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "fecundity_mean_batch_size" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "biology_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_infetion_1" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_infection_2" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_infection_3" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_infection_n" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_by_dissection_n" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_by_dissection_total" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_by_csp_n_pool" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_by_csp_total_pool" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_by_csp_percent" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_p_falciparum_n" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_p_falciparum_total" integer`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "common_occupation_1" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "common_occupation_2" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "common_occupation_3" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "outdoor_activities_at_night" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "average_wake_time" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "time_people_leave_home_in_morning" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "hours_spent_away_from_home_per_day" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_permanence_1" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval__vegetation_2" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_permanence_2" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_turbidity_3" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_permanence_3" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_7c3e6f2d75b02af02cdccbdb137" FOREIGN KEY ("vgsc995GenotypeFrequenciesFormally1014Id") REFERENCES "VgsclVgsc995fVgsc995sVgsc995cGenotypeFrequenciesFormally1014"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_4b0dbdf2c74a77b6cf870cb62ec" FOREIGN KEY ("rdl296cRdl296gRdl296sGenotypeFrequenciesId") REFERENCES "rdl296c_rdl296g_rdl296s_genotype_frequencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD CONSTRAINT "FK_0bf5af3665b0e059c7a2b0c2515" FOREIGN KEY ("ace1GenotypeFrequenciesFormally119Id") REFERENCES "ace1_genotype_frequencies_formally_119"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_0bf5af3665b0e059c7a2b0c2515"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_4b0dbdf2c74a77b6cf870cb62ec"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP CONSTRAINT "FK_7c3e6f2d75b02af02cdccbdb137"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_permanence_3"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_turbidity_3"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_permanence_2"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval__vegetation_2"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" DROP COLUMN "larval_permanence_1"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "hours_spent_away_from_home_per_day"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "time_people_leave_home_in_morning"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "average_wake_time"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "outdoor_activities_at_night"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "common_occupation_3"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "common_occupation_2"`);
        await queryRunner.query(`ALTER TABLE "environment" DROP COLUMN "common_occupation_1"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_p_falciparum_total"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_p_falciparum_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_by_csp_percent"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_by_csp_total_pool"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_by_csp_n_pool"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_by_dissection_total"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_by_dissection_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_infection_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_infection_3"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_infection_2"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sampling_infetion_1"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "biology_notes"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "fecundity_mean_batch_size"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "daily_survival_rate_percent"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "parity_percent"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_biology_n"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_biology_3"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_biology_2"`);
        await queryRunner.query(`ALTER TABLE "biology" DROP COLUMN "sampling_biology_1"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "citation_doi"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "binary_absence"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "insecticide_resistance_data"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "ace1GenotypeFrequenciesFormally119Id"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "rdl296cRdl296gRdl296sGenotypeFrequenciesId"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "vgsc995GenotypeFrequenciesFormally1014Id"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "mosquitoes_knocked_down_n"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "knock_down_exposure_time_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "mosquitoes_dead_n"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "mosquitoes_tested_n"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "concentration_micrograms"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "test_protocol"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "wild_caught_larvae_or_adults"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "bioassay_representative_of_complex_at_site_if_disaggregated_values_combined_without_adjustments"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "bioassay_representative_of_complex_at_site"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4_236m_cyp6p4_236m_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4_236m_cyp6p4_236m_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4_236wt_cyp6p4_236m_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4_236wt_cyp6p4_236m_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4_236wt_cyp6p4_236wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" DROP COLUMN "cyp6p4_236wt_cyp6p4_236wt_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114t_gste2_114t_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114t_gste2_114t_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I_gste2_114t_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I_gste2_114t_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I_gste2_114I_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" DROP COLUMN "gste2_114I_gste2_114I_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119v_gste2_119v_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119v_gste2_119v_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l_gste2_119v_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l_gste2_119v_n"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l_gste2_119l_percent"`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" DROP COLUMN "gste2_119l_gste2_119l_n"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43f_cyp4j5_43f_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43f_cyp4j5_43f_n"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l_cyp4j5_43f_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l_cyp4j5_43f_n"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l_cyp4j5_43l_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" DROP COLUMN "cyp4j5_43l_cyp4j5_43l_n"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" DROP COLUMN "cyp4j5_43f_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" DROP COLUMN "cyp4j5_43l_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" DROP COLUMN "cyp6p4_236m_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" DROP COLUMN "cyp6p4_236wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_dup1_cyp6aap_dup1_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_dup1_cyp6aap_dup1_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt_cyp6aap_dup1_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt_cyp6aap_dup1_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt.cyp6aap_wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt_cyp6aap.wt_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" DROP COLUMN "cyp6aap_dup1_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" DROP COLUMN "cyp6aap_wt_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570y_vgsc1570y_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570y_vgsc1570y_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n_1570y_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n_vgsc1570y_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n_vgsc1570n_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" DROP COLUMN "vgsc1570n_vgsc1570n_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402l_vgsc402l_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402l_vgsc402l_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v_vgsc402l_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v_vgsc402l_n"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v_vgsc402v_percent"`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" DROP COLUMN "vgsc402v_vgsc402v_n"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant_resistant_percent"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant_resistant_n"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant_susceptible_percent"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "resistant_susceptible_n"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "susceptible_susceptible_percent"`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" DROP COLUMN "susceptible_susceptible_n"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "notes_on_bioassay_linkage"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "bioassay_subsample_used_in_genotypic_test"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "genotypic_sample_linked_to_a_specific_bioassay"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "genotypic_sample_first_been_through_bioassay_tests"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "notes_on_population_representative"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "minor_species_missing_allele_frequency_data"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "genotypic_test_representative_of_species_at_site_if_disaggregated_values_combined_without_adjustments"`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" DROP COLUMN "genotypic_test_representative_of_species_at_site"`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_performance_3" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_tubidity_3" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_performance_2" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_vegetation_2" character varying`);
        await queryRunner.query(`ALTER TABLE "Larval_site" ADD "larval_performance_1" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "outdoor_activities_night" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "hours_away" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "leave_home_time" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "average_waketime" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "occupation_3" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "occupation_2" character varying`);
        await queryRunner.query(`ALTER TABLE "environment" ADD "occupation_1" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_csp_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_pf_total" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_pf_n" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_csp_total" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_csp_n" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_dissection_total" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_dissection_n" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_n" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_3" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_2" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sampling_1" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "fecundity" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "daily_survival_rate" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "parity_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_n" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_3" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_2" character varying`);
        await queryRunner.query(`ALTER TABLE "biology" ADD "sampling_1" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "ir_data" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "no_mosq_knock_down" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "knock_down_expo_time_min" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "mosquitors_dead_n" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "mosquitors_tested_n" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "concentration_microgram" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "test_protocal" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "wild_caught_larvae_adults" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "bio_rep_complex_site_disaggregated" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "bio_rep_complex_site" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4.236m_cyp6p4.236m_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4.236m_cyp6p4.236m_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4.236wt_cyp6p4.236m_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4.236wt_cyp6p4.236m_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4.236wt_cyp6p4.236wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4GenotypeFrequencies" ADD "cyp6p4.236wt_cyp6p4.236wt_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114t.gste2_114t_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114t.gste2_114t_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I.gste2_114t_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I.gste2_114t_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I.gste2_114I_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_114GenotypeFrequencies" ADD "gste2_114I.gste2_114I_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119v.gste2_119v_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119v.gste2_119v_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l.gste2_119v_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l.gste2_119v_n" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l.gste2_119l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "gste2_119GenotypeFrequencies" ADD "gste2_119l.gste2_119l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43f.cyp4j5_43f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43f.cyp4j5_43f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l.cyp4j5_43f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l.cyp4j5_43f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l.cyp4j5_43l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5GenotypeFrequencies" ADD "cyp4j5_43l.cyp4j5_43l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" ADD "cyp4j5.43f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp4j5AlleleFrequencies" ADD "cyp4j5.43l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" ADD "cyp6p4.236m_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6p4AlleleFrequencies" ADD "cyp6p4.236wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap.dup1.cyp6aap.dup1_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap.dup1.cyp6aap.dup1_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap.wt.cyp6aap.dup1_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap.wt.cyp6aap.dup1_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap.wt.cyp6aap.wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap.wt.cyp6aap.wt_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" ADD "cyp6aap.dup1_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapAlleleFrequencies" ADD "cyp6aap.wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570y.vgsc1570y_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570y.vgsc1570y_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n.1570y_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n.vgsc1570y_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n.vgsc1570n_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc1570GenotypeFrequencies" ADD "vgsc1570n.vgsc1570n_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402l.vgsc402l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402l.vgsc402l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v.vgsc402l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v.vgsc402l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v.vgsc402v_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgsc402GenotypeFrequencies" ADD "vgsc402v.vgsc402v_n" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant.resistant_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant.resistant_n" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant.susceptible_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "resistant.susceptible_n" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "susceptible.susceptible_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "kdrGenotypeFrequencies" ADD "susceptible.susceptible_n" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "notes_on_bioessay_linkage" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "bio_subsample_used_gen_test" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "gen_sample_link_spec_bio" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "gen_sample_first_bio_tests" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "notes_population_rep" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "minor_spec_miss_alle_freq_data" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "gen_test_rep_site_dis" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" ADD "gen_test_rep_site" character varying`);
        await queryRunner.query(`DROP TABLE "ace1_genotype_frequencies_formally_119"`);
        await queryRunner.query(`DROP TABLE "rdl296c_rdl296g_rdl296s_genotype_frequencies"`);
        await queryRunner.query(`DROP TABLE "VgsclVgsc995fVgsc995sVgsc995cGenotypeFrequenciesFormally1014"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "edit_logs"`);
        await queryRunner.query(`ALTER TABLE "endo_exophily" RENAME COLUMN "resting_notes" TO "notes"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" RENAME COLUMN "biting_activity_indoor_number_of_sampling_nights" TO "sampling_nights_no_indoor"`);
        await queryRunner.query(`ALTER TABLE "gsteMethodAndSample" RENAME COLUMN "gste_number_of_mosquitoes_tested" TO "gste_no_of_mosquitoes_tested"`);
        await queryRunner.query(`ALTER TABLE "ace1MethodAndSample" RENAME COLUMN "ace1_number_of_mosquitoes_tested" TO "ace1_no_of_mosquitoes_tested"`);
        await queryRunner.query(`ALTER TABLE "rdlMethodAndSample" RENAME COLUMN "rdl_number_of_mosquitoes_tested" TO "rdl_no_of_mosquitoes_tested"`);
        await queryRunner.query(`ALTER TABLE "vgsc402AlleleFrequencies" RENAME COLUMN "vgsc_402l_percent" TO "vgsc.402l_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscMethodAndSample" RENAME COLUMN "vgsc_number_of_mosquitoes_tested" TO "vgsc_no_of_mosquitors_tested"`);
        await queryRunner.query(`ALTER TABLE "sample" RENAME COLUMN "occurrence_n_total" TO "occurrence_n_tot"`);
    }

}
