import { MigrationInterface, QueryRunner } from "typeorm";

export class SecondMigrationCheck1773309203619 implements MigrationInterface {
    name = 'SecondMigrationCheck1773309203619'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
  DO $$ BEGIN
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name = 'genotypicRepresentativeness'
      AND column_name = 'genotypic_test_representative_of_species_at_site_if_disaggregat'
    ) THEN
      ALTER TABLE "genotypicRepresentativeness" 
      DROP COLUMN "genotypic_test_representative_of_species_at_site_if_disaggregat";
    END IF;
  END $$;
`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995l_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995l_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995f_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995f_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f.vgsc995f_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f.vgsc995f_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995s_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995s_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995s.vgsc995s_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995s.vgsc995s_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995c.vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995c.vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "null.vgsc995c_or_vgsc995c.vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "null.vgsc995c_or_vgsc995c.vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f.vgsc995s_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f.vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f.vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l.vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f.vgsc995s_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c.rdl296c_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c.rdl296c_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c.rdl296g_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c.rdl296g_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g.rdl296g_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g.rdl296g_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c.rdl296s_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c.rdl296s_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296s.rdl296s_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296s.rdl296s_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g.rdl296s_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g.rdl296s_percent"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g.ace1_280g_n"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g.ace1_280g_percent"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g.ace1_280s_n"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g.ace1_280s_percent"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280s.ace1_280s_n"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280s.ace1_280s_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt_cyp6aap.wt_n"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt.cyp6aap_wt_percent"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "ktd_50_percent_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "ktd_90_percent_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "ktd_95_percent_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "bioassay_representative_of_complex_at_site_if_disaggregated_val"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_p_falciparum"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "oocyst_rate"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_pv_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_pv_total"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sr_by_p_vivax"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_combined_1"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_combined_2"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_combined_3"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_combined_n"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "outdoor_host_perc"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "sampling_nights_no_indoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "sampling_nights_no_outdoor"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "biting_unit"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "18_30_21_30_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "21_30_00_30_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "00_30_03_30_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "03_30_06_30_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "sampling_nights_no_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "18_30_21_30_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "21_30_00_30_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "00_30_03_30_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "03_30_06_30_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "sampling_nights_no_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "18_30_21_30_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "21_30_00_30_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "00_30_03_30_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "03_30_06_30_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "18_00_19_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "19_00_20_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "20_00_21_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "21_00_22_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "22_00_23_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "23_00_00_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "00_00_01_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "01_00_02_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "02_00_03_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "03_00_04_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "04_00_05_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "05_00_06_00_indoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "18_00_19_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "19_00_20_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "20_00_21_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "21_00_22_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "22_00_23_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "23_00_00_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "00_00_01_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "01_00_02_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "02_00_03_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "03_00_04_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "04_00_05_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "05_00_06_00_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "18_00_19_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "19_00_20_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "20_00_21_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "21_00_22_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "22_00_23_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "23_00_00_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "00_00_01_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "01_00_02_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "02_00_03_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "03_00_04_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "04_00_05_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "05_00_06_00_outdoor"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "ir_data"`);
        await queryRunner.query(`ALTER TABLE "uploaded_dataset" ADD "va_final_check_by" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f_vgsc995f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f_vgsc995f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995s_vgsc995s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995s_vgsc995s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l_vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995c_vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995c_vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "null_vgsc995c_or_vgsc995c_vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "null_vgsc995c_or_vgsc995c_vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f_vgsc995s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f_vgsc995s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f_vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f_vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c_rdl296c__n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c_rdl296c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c_rdl296g_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c_rdl296g_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g_rdl296g_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g_rdl296g_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c_rdl296s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c_rdl296s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296s_rdl296s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296s_rdl296s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g_rdl296s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g_rdl296s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g_ace1_280g_n" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g_ace1_280g_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g_ace1_280s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g_ace1_280s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280s_ace1_280s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280s_ace1_280s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt_cyp6aap_wt_n" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt_cyp6aap_wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "bioassay_representative_of_complex_at_site_if_disaggregated_values_combined_without_adjustments" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "kdt_50_percent_min" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "kdt_90_percent_min" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "kdt_95_percent_min" character varying`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "larval_data" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "pheno_data" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "occurrence" ADD "geno_data" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_by_p_falciparum_percent" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_p_vivax_n" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_p_vivax_total" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sporozoite_rate_by_p_vivax_percent" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "oocyst_rate_percent" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "infection_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_1" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_2" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_3" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_n" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "biting_rate_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "outdoor_host_percent" double precision`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "host_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "biting_number_of_sampling_nights_indoors" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "biting_number_of_sampling_nights_outdoors" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_outdoor_biting_unit" character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "indoor_outdoor_biting_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1800_1900_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1900_2000_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2000_2100_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2100_2200_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2200_2300_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2300_0000_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0000_0100_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0100_0200_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0200_0300_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0300_0400_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0400_0500_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0500_0600_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1830_2130_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2130_0030_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0030_0330_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0330_0630_in" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "biting_activity_outdoor_number_of_sampling_nights" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1800_1900_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1900_2000_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2000_2100_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2100_2200_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2200_2300_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2300_0000_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0000_0100_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0100_0200_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0200_0300_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0300_0400_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0400_0500_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0500_0600_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1830_2130_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2130_0030_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0030_0330_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0330_0630_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "biting_activity_combined_number_of_sampling_nights" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1800_1900_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1900_2000_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2000_2100_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2100_2200_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2200_2300_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2300_0000_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0000_0100_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0100_0200_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0200_0300_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0300_0400_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0400_0500_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0500_0600_out" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "1830_2130_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "2130_0030_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0030_0330_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "0330_0630_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "biting_notes" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "final_check_by" character varying`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "insecticide_resistance_data" character varying NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "insecticide_resistance_data"`);
        await queryRunner.query(`ALTER TABLE "bionomics" DROP COLUMN "final_check_by"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "biting_notes"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0330_0630_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0030_0330_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2130_0030_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1830_2130_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0500_0600_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0400_0500_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0300_0400_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0200_0300_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0100_0200_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0000_0100_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2300_0000_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2200_2300_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2100_2200_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2000_2100_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1900_2000_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1800_1900_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "biting_activity_combined_number_of_sampling_nights"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0330_0630_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0030_0330_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2130_0030_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1830_2130_out"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0500_0600_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0400_0500_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0300_0400_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0200_0300_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0100_0200_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0000_0100_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2300_0000_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2200_2300_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2100_2200_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2000_2100_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1900_2000_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1800_1900_combined"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "biting_activity_outdoor_number_of_sampling_nights"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0330_0630_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0030_0330_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2130_0030_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1830_2130_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0500_0600_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0400_0500_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0300_0400_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0200_0300_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0100_0200_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "0000_0100_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2300_0000_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2200_2300_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2100_2200_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "2000_2100_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1900_2000_in"`);
        await queryRunner.query(`ALTER TABLE "biting_activity" DROP COLUMN "1800_1900_in"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_outdoor_biting_notes"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "indoor_outdoor_biting_unit"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "biting_number_of_sampling_nights_outdoors"`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" DROP COLUMN "biting_number_of_sampling_nights_indoors"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "host_notes"`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" DROP COLUMN "outdoor_host_percent"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "biting_rate_notes"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_n"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_3"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_2"`);
        await queryRunner.query(`ALTER TABLE "biting_rate" DROP COLUMN "abr_sampling_1"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "infection_notes"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "oocyst_rate_percent"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_by_p_vivax_percent"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_p_vivax_total"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_p_vivax_n"`);
        await queryRunner.query(`ALTER TABLE "infection" DROP COLUMN "sporozoite_rate_by_p_falciparum_percent"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "geno_data"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "pheno_data"`);
        await queryRunner.query(`ALTER TABLE "occurrence" DROP COLUMN "larval_data"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "kdt_95_percent_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "kdt_90_percent_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "kdt_50_percent_min"`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" DROP COLUMN "bioassay_representative_of_complex_at_site_if_disaggregated_values_combined_without_adjustments"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt_cyp6aap_wt_percent"`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" DROP COLUMN "cyp6aap_wt_cyp6aap_wt_n"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280s_ace1_280s_percent"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280s_ace1_280s_n"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g_ace1_280s_percent"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g_ace1_280s_n"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g_ace1_280g_percent"`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" DROP COLUMN "ace1_280g_ace1_280g_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g_rdl296s_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g_rdl296s_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296s_rdl296s_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296s_rdl296s_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c_rdl296s_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c_rdl296s_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g_rdl296g_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296g_rdl296g_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c_rdl296g_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c_rdl296g_n"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c_rdl296c_percent"`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" DROP COLUMN "rdl296c_rdl296c__n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f_vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f_vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f_vgsc995s_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f_vgsc995s_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "null_vgsc995c_or_vgsc995c_vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "null_vgsc995c_or_vgsc995c_vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995c_vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995c_vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995c_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995c_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995s_vgsc995s_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995s_vgsc995s_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995s_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995s_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f_vgsc995f_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995f_vgsc995f_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995f_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995f_n"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995l_percent"`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" DROP COLUMN "vgsc995l_vgsc995l_n"`);
        await queryRunner.query(`ALTER TABLE "uploaded_dataset" DROP COLUMN "va_final_check_by"`);
        await queryRunner.query(`ALTER TABLE "bionomics" ADD "ir_data" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "05_00_06_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "04_00_05_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "03_00_04_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "02_00_03_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "01_00_02_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "00_00_01_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "23_00_00_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "22_00_23_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "21_00_22_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "20_00_21_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "19_00_20_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "18_00_19_00_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "05_00_06_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "04_00_05_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "03_00_04_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "02_00_03_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "01_00_02_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "00_00_01_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "23_00_00_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "22_00_23_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "21_00_22_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "20_00_21_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "19_00_20_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "18_00_19_00_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "05_00_06_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "04_00_05_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "03_00_04_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "02_00_03_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "01_00_02_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "00_00_01_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "23_00_00_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "22_00_23_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "21_00_22_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "20_00_21_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "19_00_20_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "18_00_19_00_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "03_30_06_30_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "00_30_03_30_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "21_30_00_30_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "18_30_21_30_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "sampling_nights_no_combined" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "03_30_06_30_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "00_30_03_30_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "21_30_00_30_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "18_30_21_30_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "sampling_nights_no_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "03_30_06_30_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "00_30_03_30_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "21_30_00_30_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "biting_activity" ADD "18_30_21_30_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "biting_unit" character varying`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "sampling_nights_no_outdoor" integer`);
        await queryRunner.query(`ALTER TABLE "endo_exophagic" ADD "sampling_nights_no_indoor" integer`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "anthropo_zoophagic" ADD "outdoor_host_perc" double precision`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_combined_n" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_combined_3" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_combined_2" character varying`);
        await queryRunner.query(`ALTER TABLE "biting_rate" ADD "abr_sampling_combined_1" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_p_vivax" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_pv_total" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_pv_n" integer`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "oocyst_rate" double precision`);
        await queryRunner.query(`ALTER TABLE "infection" ADD "sr_by_p_falciparum" double precision`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "bioassay_representative_of_complex_at_site_if_disaggregated_val" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "ktd_95_percent_min" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "ktd_90_percent_min" character varying`);
        await queryRunner.query(`ALTER TABLE "insecticideResistanceBioassays" ADD "ktd_50_percent_min" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt.cyp6aap_wt_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "cyp6aapGenotypeFrequencies" ADD "cyp6aap_wt_cyp6aap.wt_n" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280s.ace1_280s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280s.ace1_280s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g.ace1_280s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g.ace1_280s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g.ace1_280g_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "ace1GenotypeFrequencies" ADD "ace1_280g.ace1_280g_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g.rdl296s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g.rdl296s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296s.rdl296s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296s.rdl296s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c.rdl296s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c.rdl296s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g.rdl296g_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296g.rdl296g_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c.rdl296g_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c.rdl296g_n" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c.rdl296c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "rdl296GenotypeFrequencies" ADD "rdl296c.rdl296c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f.vgsc995s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f.vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f.vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f.vgsc995s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "null.vgsc995c_or_vgsc995c.vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "null.vgsc995c_or_vgsc995c.vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995c.vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995c.vgsc995c_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995c_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995s.vgsc995s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995s.vgsc995s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995s_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995s_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f.vgsc995f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995f.vgsc995f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995f_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995f_n" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995l_percent" character varying`);
        await queryRunner.query(`ALTER TABLE "vgscGeneytpeFrequencies" ADD "vgsc995l.vgsc995l_n" character varying`);
        await queryRunner.query(`ALTER TABLE "genotypicRepresentativeness" RENAME COLUMN "genotypic_test_representative_of_species_at_site_if_disaggregated_values_combined_without_adjustments" TO "genotypic_test_representative_of_species_at_site_if_disaggregat"`);
    }

}
