export const countryList = [
  'Algeria',
  'Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cameroon',
  'Central African Republic (CAR)',
  'Chad',
  'Comoros',
  'Congo, Democratic Republic of the',
  'Congo, Republic of the',
  'Cote d’Ivoire',
  'Djibouti',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Rwanda',
  'Sao Tome and Principe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Zambia',
  'Zimbabwe',
];

export const speciesList = [
  'species',
  'Gambiae complex',
  'arabiensis',
  'coluzzii_gambiae_m form',
  'gambiae_s form_m form',
  'gambiae_s form',
  'melas',
  'merus',
  'quadriannulatus',
  'Nili complex',
  'carnevalei',
  'nili',
  'Funestus complex',
  'funestus',
  'funestus-like',
  'amharicus',
  'ardensis',
  'argenteolobatus',
  'aruni',
  'austenii',
  'azaniae',
  'azevedoi',
  'barberellus',
  'berghei',
  'bervoetsi',
  'brohieri',
  'brucei',
  'brumpti',
  'brunnipes',
  'buxtoni',
  'bwambae',
  'caliginosus',
  'cameroni',
  'caroni',
  'carteri',
  'christyi',
  'cinctus',
  'cinereus',
  'comorensis',
  'concolor',
  'confusus',
  'Coustani complex',
  'coustani',
  'cristipalpis',
  'crypticus',
  'Culicifacies complex',
  'culicifacies',
  'cydippis',
  'dancalicus',
  'daudi',
  'deemingi',
  'demeilloni',
  'distinctus',
  'domicola',
  'dthali',
  'dualaensis',
  'dureni',
  'eouzani',
  'erepens',
  'erythraeus',
  'ethiopicus',
  'faini',
  'flavicosta',
  'fontenillei',
  'fontinalis',
  'freetownensis',
  'fuscicolor',
  'fuscivenosus',
  'gabonensis',
  'garnhami',
  'gibbinsi',
  'grassei',
  'grenieri',
  'griveaudi',
  'hamoni',
  'hancocki',
  'hargreavesi',
  'harperi',
  'hervyi',
  'hughi',
  'implexus',
  'jebudensis',
  'keniensis',
  'kingi',
  'kosiensis',
  'lacani',
  'leesoni',
  'letabensis',
  'listeri',
  'lloreti',
  'longipalpis',
  'lounibosi',
  'lovettae',
  'machardyi',
  'maculipalpis',
  'maliensis',
  'Marshallii complex',
  'marshallii',
  'mascarensis',
  'millecampsi',
  'milloti',
  'mortiauxi',
  'moucheti',
  'mousinhoi',
  'multicolor',
  'multicinctus',
  'murphyi',
  'namibiensis',
  'natalensis',
  'njombiensis',
  'notleyi',
  'obscurus',
  'okuensis',
  'ovengensis',
  'paludis',
  'parensis',
  'pauliani',
  'pharoensis',
  'pretoriensis',
  'radama',
  'rageaui',
  'ranci',
  'rhodesiensis',
  'Rivulorum complex',
  'rivulorum',
  'rivulorum-like',
  'rodhaini',
  'roubaudi',
  'ruarinus',
  'rufipes',
  'salbaii',
  'schwetzi',
  'seretsei',
  'sergentii',
  'seydeli',
  'smithii',
  'somalicus',
  'squamosus',
  'stephensi',
  'swahilicus',
  'symesi',
  'tchekedii',
  'tenebrosus',
  'theileri',
  'turkhudi',
  'vaneedeni',
  'vanhoofi',
  'vernus',
  'vinckei',
  'walravensi',
  'wellcomei',
  'wilsoni',
  'ziemanni',
];
