export const countryList = [
  'Algeria',
  'Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cameroon',
  'Central African Republic (CAR)',
  'Chad',
  'Comoros',
  'Congo, Democratic Republic of the',
  'Congo, Republic of the',
  'Cote d’Ivoire',
  'Djibouti',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Rwanda',
  'Sao Tome and Principe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Zambia',
  'Zimbabwe',
];

export const speciesList = [
  'coustani',
  'pauliani',
  'comorensis',
  'ovengensis',
  'cinctus',
  'bervoetsi',
  'njombiensis',
  'okuensis',
  'berghei',
  'mortiauxi',
  'funestus-like',
  'arabiensis',
  'culicifacies',
  'fuscivenosus',
  'quadriannulatus',
  'dthali',
  'domicola',
  'fontinalis',
  'squamosus',
  'hancocki',
  'faini',
  'maculipalpis',
  'funestus',
  'buxtoni',
  'dureni',
  'jebudensis',
  'rhodesiensis',
  'grassei',
  'paludis',
  'seretsei',
  'erythraeus',
  'eouzani',
  'notleyi',
  'gabonensis',
  'hargreavesi',
  'dancalicus',
  'somalicus',
  'longipalpis',
  'kingi',
  'vernus',
  'cameroni',
  'fontenillei',
  'hervyi',
  'brucei',
  'ranci',
  'vinckei',
  'rivulorum-like',
  'radama',
  'erepens',
  'confusus',
  'austenii',
  'letabensis',
  'cydippis',
  'seydeli',
  'deemingi',
  'carteri',
  'wellcomei',
  'christyi',
  'concolor',
  'keniensis',
  'ruarinus',
  'moucheti',
  'grenieri',
  'mascarensis',
  'barberellus',
  'stephensi',
  'gibbinsi',
  'lovettae',
  'flavicosta',
  'murphyi',
  'milloti',
  'azevedoi',
  'turkhudi',
  'griveaudi',
  'brohieri',
  'roubaudi',
  'mousinhoi',
  'daudi',
  'multicolor',
  'multicinctus',
  'caroni',
  'carnevalei',
  'swahilicus',
  'cinereus',
  'harperi',
  'aruni',
  'fuscicolor',
  'ardensis',
  'nili',
  'rufipes',
  'freetownensis',
  'machardyi',
  'obscurus',
  'hamoni',
  'ziemanni',
  'dualaensis',
  'vaneedeni',
  'rivulorum',
  'walravensi',
  'garnhami',
  'vanhoofi',
  'kosiensis',
  'demeilloni',
  'argenteolobatus',
  'schwetzi',
  'natalensis',
  'marshallii',
  'ethiopicus',
  'lacani',
  'bwambae',
  'pharoensis',
  'namibiensis',
  'implexus',
  'parensis',
  'merus',
  'distinctus',
  'pretoriensis',
  'hughi',
  'gambiae',
  'gambiae (S/M)',
  'symesi',
  'listeri',
  'lounibosi',
  'caliginosus',
  'lloreti',
  'tenebrosus',
  'smithii',
  'wilsoni',
  'maliensis',
  'azaniae',
  'salbaii',
  'crypticus',
  'sergentii',
  'theileri',
  'amharicus',
  'millecampsi',
  'rageaui',
  'brunnipes',
  'brumpti',
  'leesoni',
  'tchekedii',
  'melas',
  'coluzzii',
  'cristipalpis',
  'rodhaini',
  'GAMBIAE COMPLEX',
  'FUNESTUS COMPLEX',
  'NILI COMPLEX',
  'COUSTANI COMPLEX',
  'CULICIFACIES COMPLEX',
  'MARSHALLII COMPLEX',
  'RIVULORUM COMPLEX',
];
