export const referenceCitationBionomicsValidatorCheck = {
  author: { fieldType: 'string', nullable: true },
  'publication year': { fieldType: 'number', nullable: true },
  'article title': { fieldType: 'string', nullable: true },
  'journal title': { fieldType: 'string', nullable: true },
};

export const siteBionomicsValidatorCheck = {
  country: { fieldType: 'string', nullable: false },
  site: { fieldType: 'string', nullable: false },
  'site notes': { fieldType: 'string', nullable: true },
  'MAP_DATA': { fieldType: 'string', nullable: true },
  latitude_1: { fieldType: 'string', nullable: false },
  longitude_1: { fieldType: 'string', nullable: false },
  'area type': { fieldType: 'string', nullable: true },
  'georef source': { fieldType: 'string', nullable: true },
  'GAUL code': { fieldType: 'string', nullable: true },
  'admin level_1': { fieldType: 'string', nullable: true },
  'georef notes': { fieldType: 'string', nullable: true },
};

export const recordedSpeciesBionomicsValidatorCheck = {
  ASSI: { fieldType: 'boolean', nullable: true },
  id_1: { fieldType: 'string', nullable: true },
  id_2: { fieldType: 'string', nullable: true },
  species: { fieldType: 'string', nullable: false },
  'species notes': { fieldType: 'string', nullable: true },
};

export const bionomicsValidatorCheck = {
  'adult data': { fieldType: 'boolean', nullable: true },
  'larval site data': { fieldType: 'boolean', nullable: true },
  'study/sampling design': { fieldType: 'boolean', nullable: true },
  'contact authors': { fieldType: 'boolean', nullable: true },
  'contact notes': { fieldType: 'string', nullable: true },
  'secondary or general info': { fieldType: 'boolean', nullable: true },
  'insecticide control': { fieldType: 'boolean', nullable: true },
  'ITN use?': { fieldType: 'boolean', nullable: true },
  control: { fieldType: 'string', nullable: true },
  'control notes': { fieldType: 'string', nullable: true },
  month_st: { fieldType: 'number', nullable: true },
  month_end: { fieldType: 'number', nullable: true },
  year_st: { fieldType: 'number', nullable: true },
  year_end: { fieldType: 'number', nullable: true },
  'season (given)': { fieldType: 'string', nullable: true },
  'season (calc)': { fieldType: 'string', nullable: true },
  'season notes': { fieldType: 'string', nullable: true },
  'data abstracted by': { fieldType: 'string', nullable: true },
  'data checked by': { fieldType: 'string', nullable: true },
};

export const biologyValidatorCheck = {
  'sampling (biology)_1': { fieldType: 'string', nullable: true },
  'sampling (biology)_2': { fieldType: 'string', nullable: true },
  'sampling (biology)_3': { fieldType: 'string', nullable: true },
  'sampling (biology)_n': { fieldType: 'string', nullable: true },
  'parity (n)': { fieldType: 'number', nullable: true },
  'parity (total)': { fieldType: 'number', nullable: true },
  'parity (%)': { fieldType: 'number', nullable: true },
  'daily survival rate (%)': { fieldType: 'number', nullable: true },
  'fecundity (mean batch size)': { fieldType: 'number', nullable: true },
  'gonotrophic cycle (days)': { fieldType: 'number', nullable: true },
  'biology notes': { fieldType: 'string', nullable: true },
};

export const infectionValidatorCheck = {
  'sampling (infection)_1': { fieldType: 'string', nullable: true },
  'sampling (infection)_2': { fieldType: 'string', nullable: true },
  'sampling (infection)_3': { fieldType: 'string', nullable: true },
  'sampling (infection)_n': { fieldType: 'string', nullable: true },
  'IR by CSP (n_pool)': { fieldType: 'number', nullable: true },
  'IR by CSP (total_pool)': { fieldType: 'number', nullable: true },
  'No. per pool': { fieldType: 'number', nullable: true },
  'IR by CSP (%)': { fieldType: 'number', nullable: true },
  'SR by dissection (n)': { fieldType: 'number', nullable: true },
  'SR by dissection (total)': { fieldType: 'number', nullable: true },
  'SR by dissection (%)': { fieldType: 'number', nullable: true },
  'SR by CSP (n)': { fieldType: 'number', nullable: true },
  'SR by CSP (total)': { fieldType: 'number', nullable: true },
  'SR by CSP (%)': { fieldType: 'number', nullable: true },
  'SR by Pf (n)': { fieldType: 'number', nullable: true },
  'SR by Pf (total)': { fieldType: 'number', nullable: true },
  'SR by P. falciparum': { fieldType: 'number', nullable: true },
  'SR by Pv (n)': { fieldType: 'number', nullable: true },
  'SR by Pv (total)': { fieldType: 'number', nullable: true },
  'SR by P. vivax': { fieldType: 'number', nullable: true },
  'oocyst (n)': { fieldType: 'number', nullable: true },
  'oocyst (total)': { fieldType: 'number', nullable: true },
  'oocyst rate (%)': { fieldType: 'number', nullable: true },
  EIR: { fieldType: 'number', nullable: true },
  'EIR (period)': { fieldType: 'string', nullable: true },
  'Ext. incubation period (days)': { fieldType: 'number', nullable: true },
  'infection notes': { fieldType: 'string', nullable: true },
};

export const bitingRateValidatorCheck = {
  'HBR sampling (indoor)': { fieldType: 'string', nullable: true },
  'indoor HBR': { fieldType: 'number', nullable: true },
  'HBR sampling (outdoor)': { fieldType: 'string', nullable: true },
  'outdoor HBR': { fieldType: 'number', nullable: true },
  'HBR sampling (combined)_1': { fieldType: 'string', nullable: true },
  'HBR sampling (combined)_2': { fieldType: 'string', nullable: true },
  'HBR sampling (combined)_3': { fieldType: 'string', nullable: true },
  'HBR sampling (combined)_n': { fieldType: 'string', nullable: true },
  'combined HBR': { fieldType: 'number', nullable: true },
  'HBR (unit)': { fieldType: 'string', nullable: true },
  'ABR sampling_1': { fieldType: 'string', nullable: true },
  'ABR sampling_2': { fieldType: 'string', nullable: true },
  'ABR sampling_3': { fieldType: 'string', nullable: true },
  'ABR sampling_n': { fieldType: 'string', nullable: true },
  ABR: { fieldType: 'number', nullable: true },
  'ABR unit': { fieldType: 'string', nullable: true },
  'biting rate notes': { fieldType: 'string', nullable: true },
};

export const anthropoZoophagicValidatorCheck = {
  'host sampling (indoor)': { fieldType: 'number', nullable: true },
  'indoor host (n)': { fieldType: 'number', nullable: true },
  'indoor host (total)': { fieldType: 'number', nullable: true },
  'indoor host %': { fieldType: 'number', nullable: true },
  'host sampling (outdoor)': { fieldType: 'string', nullable: true },
  'outdoor host (n)': { fieldType: 'number', nullable: true },
  'outdoor host (total)': { fieldType: 'number', nullable: true },
  'outdoor host %': { fieldType: 'number', nullable: true },
  'host sampling (combined)_1': { fieldType: 'string', nullable: true },
  'host sampling (combined)_2': { fieldType: 'string', nullable: true },
  'host sampling (combined)_3': { fieldType: 'string', nullable: true },
  'host sampling (combined)_n': { fieldType: 'string', nullable: true },
  'combined host (n)': { fieldType: 'number', nullable: true },
  'combined host (total)': { fieldType: 'number', nullable: true },
  'combined host': { fieldType: 'number', nullable: true },
  'host (unit)': { fieldType: 'string', nullable: true },
  'host sampling (other)_1': { fieldType: 'string', nullable: true },
  'host sampling (other)_2': { fieldType: 'string', nullable: true },
  'host sampling (other)_3': { fieldType: 'string', nullable: true },
  'host sampling (other)_n': { fieldType: 'string', nullable: true },
  'other host (n)': { fieldType: 'number', nullable: true },
  'other host (total)': { fieldType: 'number', nullable: true },
  'host (other)': { fieldType: 'number', nullable: true },
  'host (other) unit': { fieldType: 'string', nullable: true },
  'host notes': { fieldType: 'string', nullable: true },
};

export const endoExophagicValidatorCheck = {
  'biting -  No. of sampling nights (indoors)': {
    fieldType: 'number',
    nullable: true,
  },
  'biting sampling (indoor)': { fieldType: 'string', nullable: true },
  'indoor biting (n)': { fieldType: 'number', nullable: true },
  'indoor biting (total)': { fieldType: 'number', nullable: true },
  'indoor biting data': { fieldType: 'number', nullable: true },
  'biting -  No. of sampling nights (outdoors)': {
    fieldType: 'number',
    nullable: true,
  },
  'biting sampling (outdoor)': { fieldType: 'string', nullable: true },
  'outdoor biting (n)': { fieldType: 'number', nullable: true },
  'outdoor biting (total)': { fieldType: 'number', nullable: true },
  'outdoor biting data': { fieldType: 'number', nullable: true },
  'indoor/outdoor biting (unit)': { fieldType: 'string', nullable: true },
  'indoor/outdoor biting notes': { fieldType: 'string', nullable: true },
};

export const bitingActivityValidatorCheck = {
  'biting activity (indoor)  -  No. of sampling nights': {
    fieldType: 'number',
    nullable: true,
  },
  '18.30-21.30 (in)': { fieldType: 'number', nullable: true },
  '21.30-00.30 (in)': { fieldType: 'number', nullable: true },
  '00.30-03.30 (in)': { fieldType: 'number', nullable: true },
  '03.30-06.30 (in)': { fieldType: 'number', nullable: true },
  'biting activity (outdoor)  -  No. of sampling nights': {
    fieldType: 'number',
    nullable: true,
  },
  '18.30-21.30 (out)': { fieldType: 'number', nullable: true },
  '21.30-00.30 (out)': { fieldType: 'number', nullable: true },
  '00.30-03.30 (out)': { fieldType: 'number', nullable: true },
  '03.30-06.30 (out)': { fieldType: 'number', nullable: true },
  'biting activity (combined)  -  No. of sampling nights': {
    fieldType: 'number',
    nullable: true,
  },
  '18.30-21.30 (combined)': { fieldType: 'number', nullable: true },
  '21.30-00.30 (combined)': { fieldType: 'number', nullable: true },
  '00.30-03.30 (combined)': { fieldType: 'number', nullable: true },
  '03.30-06.30 (combined)': { fieldType: 'number', nullable: true },
  'biting notes': { fieldType: 'string', nullable: true },
};

export const endoExophilyValidatorCheck = {
  'resting sampling (indoor)': { fieldType: 'string', nullable: true },
  'unfed (indoor)': { fieldType: 'number', nullable: true },
  'fed (indoor)': { fieldType: 'number', nullable: true },
  'gravid (indoor)': { fieldType: 'number', nullable: true },
  'total (indoor)': { fieldType: 'number', nullable: true },
  'resting sampling (outdoor)': { fieldType: 'string', nullable: true },
  'unfed (outdoor)': { fieldType: 'number', nullable: true },
  'fed (outdoor)': { fieldType: 'number', nullable: true },
  'gravid (outdoor)': { fieldType: 'number', nullable: true },
  'total (outdoor)': { fieldType: 'number', nullable: true },
  'resting sampling (other)': { fieldType: 'string', nullable: true },
  'unfed (other)': { fieldType: 'number', nullable: true },
  'fed (other)': { fieldType: 'number', nullable: true },
  'gravid (other)': { fieldType: 'number', nullable: true },
  'total (other)': { fieldType: 'number', nullable: true },
  'resting (unit)': { fieldType: 'string', nullable: true },
  'resting notes': { fieldType: 'string', nullable: true },
};

export const environmentValidatorCheck = {
  roof: { fieldType: 'string', nullable: true },
  walls: { fieldType: 'string', nullable: true },
  'house screening': { fieldType: 'string', nullable: true },
  'open eaves': { fieldType: 'string', nullable: true },
  cooking: { fieldType: 'string', nullable: true },
  'housing notes': { fieldType: 'string', nullable: true },
  'common occupation_1': { fieldType: 'string', nullable: true },
  'common occupation_2': { fieldType: 'string', nullable: true },
  'common occupation_3': { fieldType: 'string', nullable: true },
  'outdoor activities at night': { fieldType: 'string', nullable: true },
  'sleeping outdoors': { fieldType: 'string', nullable: true },
  'outdoor timings/hours': { fieldType: 'string', nullable: true },
  'outdoor activities notes': { fieldType: 'string', nullable: true },
  'average bedtime': { fieldType: 'string', nullable: true },
  'average wake time': { fieldType: 'string', nullable: true },
  'time people leave home  in morning': { fieldType: 'string', nullable: true },
  'hours spent away from home per day': { fieldType: 'string', nullable: true },
  'seasonal labour': { fieldType: 'string', nullable: true },
  'community notes': { fieldType: 'string', nullable: true },
  farming: { fieldType: 'string', nullable: true },
  'farming notes': { fieldType: 'string', nullable: true },
  livestock_1: { fieldType: 'string', nullable: true },
  livestock_2: { fieldType: 'string', nullable: true },
  livestock_3: { fieldType: 'string', nullable: true },
  livestock_4: { fieldType: 'string', nullable: true },
  'livestock notes': { fieldType: 'string', nullable: true },
  'local plants': { fieldType: 'string', nullable: true },
  'environment notes': { fieldType: 'string', nullable: true },
};
