name: Deploy with Docker Compose

on:
  push:
    branches:
       - test # Trigger on push to the `main` branch
  workflow_dispatch: # Enable manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Sync files to the deployment server
    # - name: Copy Docker Compose files to the server
    #   uses: appleboy/scp-action@v0.2.4
    #   with:
    #     host: ${{ secrets.DEPLOYMENT_SERVER }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     source: ./docker-compose.uat.yml
    #     target: ~/vectoratlas-software-code/src/Docker

    # Step 4: SSH into the server and deploy
    - name: Run docker-compose up on the server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER_UAT }}
        username: ${{ secrets.SSH_USER_UAT }}
        key: ${{ secrets.SSH_PRIVATE_KEY_UAT }}
        script: |
          cd ~/vectoratlas-software-code/src/Docker
          # docker compose -f docker-compose.uat.yml pull # Pull the latest images from GHCR
          docker compose up -f docker-compose.uat.yml -d # Start the containers
