name: Deploy Vector Atlas to test environment
on: workflow_dispatch
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH in and run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: 20.87.47.170
        username: vectoratlasadmin
        key: ${{ secrets.TEST_SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: ls -la
