name: Deploy Vector Atlas to test environment
on: 
  workflow_dispatch:
    inputs:
      gitCommitSha:
        description: 'The sha of the git commit to deploy'
        required: true
jobs:
  build:
    name: Deploy
    environment: test-environment
    runs-on: ubuntu-latest
    steps:
    - name: SSH in and run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: 20.87.47.170
        username: vectoratlasadmin
        key: ${{ secrets.TEST_SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export VA_DB_USER="${{ secrets.TEST_SERVER_DB_USER }}"
          export VA_DB_PASSWORD="${{ secrets.TEST_SERVER_DB_PASSWORD }}"
          export VA_TOKEN_SECRET="${{ secrets.TEST_SERVER_TOKEN_SECRET }}"
          export VA_DB_URL="${{ secrets.TEST_SERVER_DB_URL }}"
          cd ~/vector-atlas/vectoratlas-software-code/
          chmod +x deployEnvironment.sh
          ./deployEnvironment.sh ${{ github.event.inputs.gitCommitSha }}
