name: Build and Push Docker Images

on:
  push:
    branches:
      - test  # Replace with the branch you want to trigger this workflow
  pull_request:
    branches:
      - test

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        env:
          IMAGE_TAG: latest
        run: |
          # Define directories and image names
          directories=("src/API" "src/UI" "src/Help" "src/TileServer" "src/Docker/umami" "src/IngestionAPI" "src/Docker/nginx")
          for dir in "${directories[@]}"; do
            # Remove 'src/' and convert to lowercase for image name
            image_name=$(echo "$dir" | sed 's|^src/||; s|/|-|g' | tr '[:upper:]' '[:lower:]')
            full_image_name="ghcr.io/${{ github.repository_owner }}/${image_name}:${IMAGE_TAG}"
            
            echo "Building image for $dir..."
            docker build -t "$full_image_name" "$dir"
            
            echo "Pushing image $full_image_name..."
            docker push "$full_image_name"
          done

