name: PR CI

on:
  pull_request:
    branches: ["main", "test"]

jobs:
  set-environment:
    name: Set the GitHub environment to use based on git branch.
    runs-on: ubuntu-latest
    outputs:
      github_env: ${{ steps.determine-env.outputs.ENV_TARGET }}
    steps:
      - id: determine-env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "ENV_TARGET=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" = "test" ]; then
            echo "ENV_TARGET=test" >> $GITHUB_OUTPUT
          fi

  detect-changes:
    name: Check for file changes in (${{ needs.determine-env.outputs.github_env }}) environment
    needs: set-environment
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      ui: ${{ steps.changes.outputs.ui }}
      occurrencegeojob: ${{ steps.changes.outputs.occurrencegeojob }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'src/API/**'
              - '.github/**'
            ui:
              - 'src/UI/**'
              - '.github/**'
            occurrencegeojob:
              - 'src/OccurrenceGeoJob/**'
              - '.github/**'

  build-occurrencegeojob:
    name: Build & Test Occurrence Geo Job in (${{ needs.determine-env.outputs.github_env }})
    needs: [set-environment, detect-changes]
    if: needs.detect-changes.outputs.occurrencegeojob == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/OccurrenceGeoJob
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  skip-occurrencegeojob:
    name: Skip Build - No OccurrenceGeoJob Changes in (${{ needs.determine-env.outputs.github_env }})
    if: needs.detect-changes.outputs.occurrencegeojob != 'true'
    needs: [set-environment, detect-changes]
    runs-on: ubuntu-latest
    steps:
      - run: echo "No OccurrenceGeoJob changes. Skipping OccurrenceGeoJob build."

  build-api:
    name: Build & Test API in (${{ needs.determine-env.outputs.github_env }})
    needs: [set-environment, detect-changes]
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/API
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  skip-api:
    name: Skip Build - No API Changes in (${{ needs.determine-env.outputs.github_env }})
    needs: [set-environment, detect-changes]
    if: needs.detect-changes.outputs.api != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No API changes. Skipping API build."

  build-ui:
    name: Build & Test UI in (${{ needs.determine-env.outputs.github_env }})
    needs: [set-environment, detect-changes]
    if: needs.detect-changes.outputs.ui == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/UI
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  skip-ui:
    name: Skip Build - No UI Changes in (${{ needs.determine-env.outputs.github_env }})
    needs: [set-environment, detect-changes]
    if: needs.detect-changes.outputs.ui != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No UI changes. Skipping UI build."
