name: UI CI

on:
  pull_request:
    branches: [ "main", "test" ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      ui: ${{ steps.changes.outputs.ui }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            ui:
              - 'src/UI/**'
              - '.github/**'

  build-ui:
    name: Build & Test UI
    needs: detect-changes
    if: needs.detect-changes.outputs.ui == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/UI
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      # Uncomment if needed
      # - name: Test
      #   run: npm run test:ci
